<?php

/**
 * Base class that represents a row from the 'student' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov 28 13:47:54 2011
 *
 * @package    lib.model.om
 */
abstract class BaseStudent extends BaseObject  implements Persistent {


  const PEER = 'StudentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        StudentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the fmid field.
	 * @var        int
	 */
	protected $fmid;

	/**
	 * The value for the first_name field.
	 * @var        string
	 */
	protected $first_name;

	/**
	 * The value for the last_name field.
	 * @var        string
	 */
	protected $last_name;

	/**
	 * The value for the email field.
	 * @var        string
	 */
	protected $email;

	/**
	 * The value for the reset_key field.
	 * @var        string
	 */
	protected $reset_key;

	/**
	 * The value for the new_email field.
	 * @var        string
	 */
	protected $new_email;

	/**
	 * The value for the new_email_request_time field.
	 * @var        string
	 */
	protected $new_email_request_time;

	/**
	 * The value for the home_address field.
	 * @var        string
	 */
	protected $home_address;

	/**
	 * The value for the city field.
	 * @var        string
	 */
	protected $city;

	/**
	 * The value for the state_prov field.
	 * @var        string
	 */
	protected $state_prov;

	/**
	 * The value for the country field.
	 * @var        string
	 */
	protected $country;

	/**
	 * The value for the zip_postal field.
	 * @var        string
	 */
	protected $zip_postal;

	/**
	 * The value for the home_phone field.
	 * @var        string
	 */
	protected $home_phone;

	/**
	 * The value for the cell_phone field.
	 * @var        string
	 */
	protected $cell_phone;

	/**
	 * The value for the business_phone field.
	 * @var        string
	 */
	protected $business_phone;

	/**
	 * The value for the level field.
	 * @var        int
	 */
	protected $level;

	/**
	 * The value for the password field.
	 * @var        string
	 */
	protected $password;

	/**
	 * The value for the salt field.
	 * @var        string
	 */
	protected $salt;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the extra1 field.
	 * @var        string
	 */
	protected $extra1;

	/**
	 * The value for the extra2 field.
	 * @var        string
	 */
	protected $extra2;

	/**
	 * The value for the extra3 field.
	 * @var        string
	 */
	protected $extra3;

	/**
	 * The value for the extra4 field.
	 * @var        string
	 */
	protected $extra4;

	/**
	 * The value for the extra5 field.
	 * @var        string
	 */
	protected $extra5;

	/**
	 * The value for the extra6 field.
	 * @var        string
	 */
	protected $extra6;

	/**
	 * The value for the extra7 field.
	 * @var        string
	 */
	protected $extra7;

	/**
	 * The value for the extra8 field.
	 * @var        string
	 */
	protected $extra8;

	/**
	 * The value for the extra9 field.
	 * @var        string
	 */
	protected $extra9;

	/**
	 * The value for the extra10 field.
	 * @var        string
	 */
	protected $extra10;

	/**
	 * The value for the extra11 field.
	 * @var        string
	 */
	protected $extra11;

	/**
	 * The value for the extra12 field.
	 * @var        string
	 */
	protected $extra12;

	/**
	 * The value for the extra13 field.
	 * @var        string
	 */
	protected $extra13;

	/**
	 * The value for the extra14 field.
	 * @var        string
	 */
	protected $extra14;

	/**
	 * The value for the extra15 field.
	 * @var        string
	 */
	protected $extra15;

	/**
	 * The value for the extra16 field.
	 * @var        string
	 */
	protected $extra16;

	/**
	 * The value for the extra17 field.
	 * @var        string
	 */
	protected $extra17;

	/**
	 * The value for the extra18 field.
	 * @var        string
	 */
	protected $extra18;

	/**
	 * The value for the extra19 field.
	 * @var        string
	 */
	protected $extra19;

	/**
	 * The value for the extra20 field.
	 * @var        string
	 */
	protected $extra20;

	/**
	 * @var        array Enrollment[] Collection to store aggregation of Enrollment objects.
	 */
	protected $collEnrollments;

	/**
	 * @var        Criteria The criteria used to select the current contents of collEnrollments.
	 */
	private $lastEnrollmentCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseStudent object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [fmid] column value.
	 * 
	 * @return     int
	 */
	public function getFmid()
	{
		return $this->fmid;
	}

	/**
	 * Get the [first_name] column value.
	 * 
	 * @return     string
	 */
	public function getFirstName()
	{
		return $this->first_name;
	}

	/**
	 * Get the [last_name] column value.
	 * 
	 * @return     string
	 */
	public function getLastName()
	{
		return $this->last_name;
	}

	/**
	 * Get the [email] column value.
	 * 
	 * @return     string
	 */
	public function getEmail()
	{
		return $this->email;
	}

	/**
	 * Get the [reset_key] column value.
	 * 
	 * @return     string
	 */
	public function getResetKey()
	{
		return $this->reset_key;
	}

	/**
	 * Get the [new_email] column value.
	 * 
	 * @return     string
	 */
	public function getNewEmail()
	{
		return $this->new_email;
	}

	/**
	 * Get the [optionally formatted] temporal [new_email_request_time] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getNewEmailRequestTime($format = 'Y-m-d H:i:s')
	{
		if ($this->new_email_request_time === null) {
			return null;
		}


		if ($this->new_email_request_time === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->new_email_request_time);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->new_email_request_time, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [home_address] column value.
	 * 
	 * @return     string
	 */
	public function getHomeAddress()
	{
		return $this->home_address;
	}

	/**
	 * Get the [city] column value.
	 * 
	 * @return     string
	 */
	public function getCity()
	{
		return $this->city;
	}

	/**
	 * Get the [state_prov] column value.
	 * 
	 * @return     string
	 */
	public function getStateProv()
	{
		return $this->state_prov;
	}

	/**
	 * Get the [country] column value.
	 * 
	 * @return     string
	 */
	public function getCountry()
	{
		return $this->country;
	}

	/**
	 * Get the [zip_postal] column value.
	 * 
	 * @return     string
	 */
	public function getZipPostal()
	{
		return $this->zip_postal;
	}

	/**
	 * Get the [home_phone] column value.
	 * 
	 * @return     string
	 */
	public function getHomePhone()
	{
		return $this->home_phone;
	}

	/**
	 * Get the [cell_phone] column value.
	 * 
	 * @return     string
	 */
	public function getCellPhone()
	{
		return $this->cell_phone;
	}

	/**
	 * Get the [business_phone] column value.
	 * 
	 * @return     string
	 */
	public function getBusinessPhone()
	{
		return $this->business_phone;
	}

	/**
	 * Get the [level] column value.
	 * 
	 * @return     int
	 */
	public function getLevel()
	{
		return $this->level;
	}

	/**
	 * Get the [password] column value.
	 * 
	 * @return     string
	 */
	public function getPassword()
	{
		return $this->password;
	}

	/**
	 * Get the [salt] column value.
	 * 
	 * @return     string
	 */
	public function getSalt()
	{
		return $this->salt;
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [extra1] column value.
	 * 
	 * @return     string
	 */
	public function getExtra1()
	{
		return $this->extra1;
	}

	/**
	 * Get the [extra2] column value.
	 * 
	 * @return     string
	 */
	public function getExtra2()
	{
		return $this->extra2;
	}

	/**
	 * Get the [extra3] column value.
	 * 
	 * @return     string
	 */
	public function getExtra3()
	{
		return $this->extra3;
	}

	/**
	 * Get the [extra4] column value.
	 * 
	 * @return     string
	 */
	public function getExtra4()
	{
		return $this->extra4;
	}

	/**
	 * Get the [extra5] column value.
	 * 
	 * @return     string
	 */
	public function getExtra5()
	{
		return $this->extra5;
	}

	/**
	 * Get the [extra6] column value.
	 * 
	 * @return     string
	 */
	public function getExtra6()
	{
		return $this->extra6;
	}

	/**
	 * Get the [extra7] column value.
	 * 
	 * @return     string
	 */
	public function getExtra7()
	{
		return $this->extra7;
	}

	/**
	 * Get the [extra8] column value.
	 * 
	 * @return     string
	 */
	public function getExtra8()
	{
		return $this->extra8;
	}

	/**
	 * Get the [extra9] column value.
	 * 
	 * @return     string
	 */
	public function getExtra9()
	{
		return $this->extra9;
	}

	/**
	 * Get the [extra10] column value.
	 * 
	 * @return     string
	 */
	public function getExtra10()
	{
		return $this->extra10;
	}

	/**
	 * Get the [extra11] column value.
	 * 
	 * @return     string
	 */
	public function getExtra11()
	{
		return $this->extra11;
	}

	/**
	 * Get the [extra12] column value.
	 * 
	 * @return     string
	 */
	public function getExtra12()
	{
		return $this->extra12;
	}

	/**
	 * Get the [extra13] column value.
	 * 
	 * @return     string
	 */
	public function getExtra13()
	{
		return $this->extra13;
	}

	/**
	 * Get the [extra14] column value.
	 * 
	 * @return     string
	 */
	public function getExtra14()
	{
		return $this->extra14;
	}

	/**
	 * Get the [extra15] column value.
	 * 
	 * @return     string
	 */
	public function getExtra15()
	{
		return $this->extra15;
	}

	/**
	 * Get the [extra16] column value.
	 * 
	 * @return     string
	 */
	public function getExtra16()
	{
		return $this->extra16;
	}

	/**
	 * Get the [extra17] column value.
	 * 
	 * @return     string
	 */
	public function getExtra17()
	{
		return $this->extra17;
	}

	/**
	 * Get the [extra18] column value.
	 * 
	 * @return     string
	 */
	public function getExtra18()
	{
		return $this->extra18;
	}

	/**
	 * Get the [extra19] column value.
	 * 
	 * @return     string
	 */
	public function getExtra19()
	{
		return $this->extra19;
	}

	/**
	 * Get the [extra20] column value.
	 * 
	 * @return     string
	 */
	public function getExtra20()
	{
		return $this->extra20;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = StudentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [fmid] column.
	 * 
	 * @param      int $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setFmid($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fmid !== $v) {
			$this->fmid = $v;
			$this->modifiedColumns[] = StudentPeer::FMID;
		}

		return $this;
	} // setFmid()

	/**
	 * Set the value of [first_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setFirstName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->first_name !== $v) {
			$this->first_name = $v;
			$this->modifiedColumns[] = StudentPeer::FIRST_NAME;
		}

		return $this;
	} // setFirstName()

	/**
	 * Set the value of [last_name] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setLastName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->last_name !== $v) {
			$this->last_name = $v;
			$this->modifiedColumns[] = StudentPeer::LAST_NAME;
		}

		return $this;
	} // setLastName()

	/**
	 * Set the value of [email] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->email !== $v) {
			$this->email = $v;
			$this->modifiedColumns[] = StudentPeer::EMAIL;
		}

		return $this;
	} // setEmail()

	/**
	 * Set the value of [reset_key] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setResetKey($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->reset_key !== $v) {
			$this->reset_key = $v;
			$this->modifiedColumns[] = StudentPeer::RESET_KEY;
		}

		return $this;
	} // setResetKey()

	/**
	 * Set the value of [new_email] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setNewEmail($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->new_email !== $v) {
			$this->new_email = $v;
			$this->modifiedColumns[] = StudentPeer::NEW_EMAIL;
		}

		return $this;
	} // setNewEmail()

	/**
	 * Sets the value of [new_email_request_time] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Student The current object (for fluent API support)
	 */
	public function setNewEmailRequestTime($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->new_email_request_time !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->new_email_request_time !== null && $tmpDt = new DateTime($this->new_email_request_time)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->new_email_request_time = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = StudentPeer::NEW_EMAIL_REQUEST_TIME;
			}
		} // if either are not null

		return $this;
	} // setNewEmailRequestTime()

	/**
	 * Set the value of [home_address] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setHomeAddress($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->home_address !== $v) {
			$this->home_address = $v;
			$this->modifiedColumns[] = StudentPeer::HOME_ADDRESS;
		}

		return $this;
	} // setHomeAddress()

	/**
	 * Set the value of [city] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setCity($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->city !== $v) {
			$this->city = $v;
			$this->modifiedColumns[] = StudentPeer::CITY;
		}

		return $this;
	} // setCity()

	/**
	 * Set the value of [state_prov] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setStateProv($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->state_prov !== $v) {
			$this->state_prov = $v;
			$this->modifiedColumns[] = StudentPeer::STATE_PROV;
		}

		return $this;
	} // setStateProv()

	/**
	 * Set the value of [country] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setCountry($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->country !== $v) {
			$this->country = $v;
			$this->modifiedColumns[] = StudentPeer::COUNTRY;
		}

		return $this;
	} // setCountry()

	/**
	 * Set the value of [zip_postal] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setZipPostal($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->zip_postal !== $v) {
			$this->zip_postal = $v;
			$this->modifiedColumns[] = StudentPeer::ZIP_POSTAL;
		}

		return $this;
	} // setZipPostal()

	/**
	 * Set the value of [home_phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setHomePhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->home_phone !== $v) {
			$this->home_phone = $v;
			$this->modifiedColumns[] = StudentPeer::HOME_PHONE;
		}

		return $this;
	} // setHomePhone()

	/**
	 * Set the value of [cell_phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setCellPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->cell_phone !== $v) {
			$this->cell_phone = $v;
			$this->modifiedColumns[] = StudentPeer::CELL_PHONE;
		}

		return $this;
	} // setCellPhone()

	/**
	 * Set the value of [business_phone] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setBusinessPhone($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->business_phone !== $v) {
			$this->business_phone = $v;
			$this->modifiedColumns[] = StudentPeer::BUSINESS_PHONE;
		}

		return $this;
	} // setBusinessPhone()

	/**
	 * Set the value of [level] column.
	 * 
	 * @param      int $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setLevel($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->level !== $v) {
			$this->level = $v;
			$this->modifiedColumns[] = StudentPeer::LEVEL;
		}

		return $this;
	} // setLevel()

	/**
	 * Set the value of [password] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setPassword($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->password !== $v) {
			$this->password = $v;
			$this->modifiedColumns[] = StudentPeer::PASSWORD;
		}

		return $this;
	} // setPassword()

	/**
	 * Set the value of [salt] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setSalt($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->salt !== $v) {
			$this->salt = $v;
			$this->modifiedColumns[] = StudentPeer::SALT;
		}

		return $this;
	} // setSalt()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Student The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = StudentPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Student The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = StudentPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Set the value of [extra1] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra1 !== $v) {
			$this->extra1 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA1;
		}

		return $this;
	} // setExtra1()

	/**
	 * Set the value of [extra2] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra2 !== $v) {
			$this->extra2 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA2;
		}

		return $this;
	} // setExtra2()

	/**
	 * Set the value of [extra3] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra3($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra3 !== $v) {
			$this->extra3 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA3;
		}

		return $this;
	} // setExtra3()

	/**
	 * Set the value of [extra4] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra4($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra4 !== $v) {
			$this->extra4 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA4;
		}

		return $this;
	} // setExtra4()

	/**
	 * Set the value of [extra5] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra5($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra5 !== $v) {
			$this->extra5 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA5;
		}

		return $this;
	} // setExtra5()

	/**
	 * Set the value of [extra6] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra6($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra6 !== $v) {
			$this->extra6 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA6;
		}

		return $this;
	} // setExtra6()

	/**
	 * Set the value of [extra7] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra7($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra7 !== $v) {
			$this->extra7 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA7;
		}

		return $this;
	} // setExtra7()

	/**
	 * Set the value of [extra8] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra8($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra8 !== $v) {
			$this->extra8 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA8;
		}

		return $this;
	} // setExtra8()

	/**
	 * Set the value of [extra9] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra9($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra9 !== $v) {
			$this->extra9 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA9;
		}

		return $this;
	} // setExtra9()

	/**
	 * Set the value of [extra10] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra10($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra10 !== $v) {
			$this->extra10 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA10;
		}

		return $this;
	} // setExtra10()

	/**
	 * Set the value of [extra11] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra11($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra11 !== $v) {
			$this->extra11 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA11;
		}

		return $this;
	} // setExtra11()

	/**
	 * Set the value of [extra12] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra12($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra12 !== $v) {
			$this->extra12 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA12;
		}

		return $this;
	} // setExtra12()

	/**
	 * Set the value of [extra13] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra13($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra13 !== $v) {
			$this->extra13 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA13;
		}

		return $this;
	} // setExtra13()

	/**
	 * Set the value of [extra14] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra14($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra14 !== $v) {
			$this->extra14 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA14;
		}

		return $this;
	} // setExtra14()

	/**
	 * Set the value of [extra15] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra15($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra15 !== $v) {
			$this->extra15 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA15;
		}

		return $this;
	} // setExtra15()

	/**
	 * Set the value of [extra16] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra16($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra16 !== $v) {
			$this->extra16 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA16;
		}

		return $this;
	} // setExtra16()

	/**
	 * Set the value of [extra17] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra17($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra17 !== $v) {
			$this->extra17 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA17;
		}

		return $this;
	} // setExtra17()

	/**
	 * Set the value of [extra18] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra18($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra18 !== $v) {
			$this->extra18 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA18;
		}

		return $this;
	} // setExtra18()

	/**
	 * Set the value of [extra19] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra19($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra19 !== $v) {
			$this->extra19 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA19;
		}

		return $this;
	} // setExtra19()

	/**
	 * Set the value of [extra20] column.
	 * 
	 * @param      string $v new value
	 * @return     Student The current object (for fluent API support)
	 */
	public function setExtra20($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra20 !== $v) {
			$this->extra20 = $v;
			$this->modifiedColumns[] = StudentPeer::EXTRA20;
		}

		return $this;
	} // setExtra20()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->fmid = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->first_name = ($row[$startcol + 2] !== null) ? (string) $row[$startcol + 2] : null;
			$this->last_name = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->email = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->reset_key = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->new_email = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->new_email_request_time = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->home_address = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->city = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->state_prov = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->country = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->zip_postal = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->home_phone = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->cell_phone = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->business_phone = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->level = ($row[$startcol + 16] !== null) ? (int) $row[$startcol + 16] : null;
			$this->password = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->salt = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->created_at = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->updated_at = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->extra1 = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->extra2 = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->extra3 = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->extra4 = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->extra5 = ($row[$startcol + 25] !== null) ? (string) $row[$startcol + 25] : null;
			$this->extra6 = ($row[$startcol + 26] !== null) ? (string) $row[$startcol + 26] : null;
			$this->extra7 = ($row[$startcol + 27] !== null) ? (string) $row[$startcol + 27] : null;
			$this->extra8 = ($row[$startcol + 28] !== null) ? (string) $row[$startcol + 28] : null;
			$this->extra9 = ($row[$startcol + 29] !== null) ? (string) $row[$startcol + 29] : null;
			$this->extra10 = ($row[$startcol + 30] !== null) ? (string) $row[$startcol + 30] : null;
			$this->extra11 = ($row[$startcol + 31] !== null) ? (string) $row[$startcol + 31] : null;
			$this->extra12 = ($row[$startcol + 32] !== null) ? (string) $row[$startcol + 32] : null;
			$this->extra13 = ($row[$startcol + 33] !== null) ? (string) $row[$startcol + 33] : null;
			$this->extra14 = ($row[$startcol + 34] !== null) ? (string) $row[$startcol + 34] : null;
			$this->extra15 = ($row[$startcol + 35] !== null) ? (string) $row[$startcol + 35] : null;
			$this->extra16 = ($row[$startcol + 36] !== null) ? (string) $row[$startcol + 36] : null;
			$this->extra17 = ($row[$startcol + 37] !== null) ? (string) $row[$startcol + 37] : null;
			$this->extra18 = ($row[$startcol + 38] !== null) ? (string) $row[$startcol + 38] : null;
			$this->extra19 = ($row[$startcol + 39] !== null) ? (string) $row[$startcol + 39] : null;
			$this->extra20 = ($row[$startcol + 40] !== null) ? (string) $row[$startcol + 40] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 41; // 41 = StudentPeer::NUM_COLUMNS - StudentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Student object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = StudentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collEnrollments = null;
			$this->lastEnrollmentCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudent:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			StudentPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseStudent:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudent:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isNew() && !$this->isColumnModified(StudentPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

    if ($this->isModified() && !$this->isColumnModified(StudentPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseStudent:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			StudentPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = StudentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = StudentPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += StudentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collEnrollments !== null) {
				foreach ($this->collEnrollments as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = StudentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collEnrollments !== null) {
					foreach ($this->collEnrollments as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = StudentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getFmid();
				break;
			case 2:
				return $this->getFirstName();
				break;
			case 3:
				return $this->getLastName();
				break;
			case 4:
				return $this->getEmail();
				break;
			case 5:
				return $this->getResetKey();
				break;
			case 6:
				return $this->getNewEmail();
				break;
			case 7:
				return $this->getNewEmailRequestTime();
				break;
			case 8:
				return $this->getHomeAddress();
				break;
			case 9:
				return $this->getCity();
				break;
			case 10:
				return $this->getStateProv();
				break;
			case 11:
				return $this->getCountry();
				break;
			case 12:
				return $this->getZipPostal();
				break;
			case 13:
				return $this->getHomePhone();
				break;
			case 14:
				return $this->getCellPhone();
				break;
			case 15:
				return $this->getBusinessPhone();
				break;
			case 16:
				return $this->getLevel();
				break;
			case 17:
				return $this->getPassword();
				break;
			case 18:
				return $this->getSalt();
				break;
			case 19:
				return $this->getCreatedAt();
				break;
			case 20:
				return $this->getUpdatedAt();
				break;
			case 21:
				return $this->getExtra1();
				break;
			case 22:
				return $this->getExtra2();
				break;
			case 23:
				return $this->getExtra3();
				break;
			case 24:
				return $this->getExtra4();
				break;
			case 25:
				return $this->getExtra5();
				break;
			case 26:
				return $this->getExtra6();
				break;
			case 27:
				return $this->getExtra7();
				break;
			case 28:
				return $this->getExtra8();
				break;
			case 29:
				return $this->getExtra9();
				break;
			case 30:
				return $this->getExtra10();
				break;
			case 31:
				return $this->getExtra11();
				break;
			case 32:
				return $this->getExtra12();
				break;
			case 33:
				return $this->getExtra13();
				break;
			case 34:
				return $this->getExtra14();
				break;
			case 35:
				return $this->getExtra15();
				break;
			case 36:
				return $this->getExtra16();
				break;
			case 37:
				return $this->getExtra17();
				break;
			case 38:
				return $this->getExtra18();
				break;
			case 39:
				return $this->getExtra19();
				break;
			case 40:
				return $this->getExtra20();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = StudentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getFmid(),
			$keys[2] => $this->getFirstName(),
			$keys[3] => $this->getLastName(),
			$keys[4] => $this->getEmail(),
			$keys[5] => $this->getResetKey(),
			$keys[6] => $this->getNewEmail(),
			$keys[7] => $this->getNewEmailRequestTime(),
			$keys[8] => $this->getHomeAddress(),
			$keys[9] => $this->getCity(),
			$keys[10] => $this->getStateProv(),
			$keys[11] => $this->getCountry(),
			$keys[12] => $this->getZipPostal(),
			$keys[13] => $this->getHomePhone(),
			$keys[14] => $this->getCellPhone(),
			$keys[15] => $this->getBusinessPhone(),
			$keys[16] => $this->getLevel(),
			$keys[17] => $this->getPassword(),
			$keys[18] => $this->getSalt(),
			$keys[19] => $this->getCreatedAt(),
			$keys[20] => $this->getUpdatedAt(),
			$keys[21] => $this->getExtra1(),
			$keys[22] => $this->getExtra2(),
			$keys[23] => $this->getExtra3(),
			$keys[24] => $this->getExtra4(),
			$keys[25] => $this->getExtra5(),
			$keys[26] => $this->getExtra6(),
			$keys[27] => $this->getExtra7(),
			$keys[28] => $this->getExtra8(),
			$keys[29] => $this->getExtra9(),
			$keys[30] => $this->getExtra10(),
			$keys[31] => $this->getExtra11(),
			$keys[32] => $this->getExtra12(),
			$keys[33] => $this->getExtra13(),
			$keys[34] => $this->getExtra14(),
			$keys[35] => $this->getExtra15(),
			$keys[36] => $this->getExtra16(),
			$keys[37] => $this->getExtra17(),
			$keys[38] => $this->getExtra18(),
			$keys[39] => $this->getExtra19(),
			$keys[40] => $this->getExtra20(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = StudentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setFmid($value);
				break;
			case 2:
				$this->setFirstName($value);
				break;
			case 3:
				$this->setLastName($value);
				break;
			case 4:
				$this->setEmail($value);
				break;
			case 5:
				$this->setResetKey($value);
				break;
			case 6:
				$this->setNewEmail($value);
				break;
			case 7:
				$this->setNewEmailRequestTime($value);
				break;
			case 8:
				$this->setHomeAddress($value);
				break;
			case 9:
				$this->setCity($value);
				break;
			case 10:
				$this->setStateProv($value);
				break;
			case 11:
				$this->setCountry($value);
				break;
			case 12:
				$this->setZipPostal($value);
				break;
			case 13:
				$this->setHomePhone($value);
				break;
			case 14:
				$this->setCellPhone($value);
				break;
			case 15:
				$this->setBusinessPhone($value);
				break;
			case 16:
				$this->setLevel($value);
				break;
			case 17:
				$this->setPassword($value);
				break;
			case 18:
				$this->setSalt($value);
				break;
			case 19:
				$this->setCreatedAt($value);
				break;
			case 20:
				$this->setUpdatedAt($value);
				break;
			case 21:
				$this->setExtra1($value);
				break;
			case 22:
				$this->setExtra2($value);
				break;
			case 23:
				$this->setExtra3($value);
				break;
			case 24:
				$this->setExtra4($value);
				break;
			case 25:
				$this->setExtra5($value);
				break;
			case 26:
				$this->setExtra6($value);
				break;
			case 27:
				$this->setExtra7($value);
				break;
			case 28:
				$this->setExtra8($value);
				break;
			case 29:
				$this->setExtra9($value);
				break;
			case 30:
				$this->setExtra10($value);
				break;
			case 31:
				$this->setExtra11($value);
				break;
			case 32:
				$this->setExtra12($value);
				break;
			case 33:
				$this->setExtra13($value);
				break;
			case 34:
				$this->setExtra14($value);
				break;
			case 35:
				$this->setExtra15($value);
				break;
			case 36:
				$this->setExtra16($value);
				break;
			case 37:
				$this->setExtra17($value);
				break;
			case 38:
				$this->setExtra18($value);
				break;
			case 39:
				$this->setExtra19($value);
				break;
			case 40:
				$this->setExtra20($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = StudentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFmid($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFirstName($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setLastName($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setEmail($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setResetKey($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setNewEmail($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setNewEmailRequestTime($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setHomeAddress($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setCity($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setStateProv($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setCountry($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setZipPostal($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setHomePhone($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setCellPhone($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setBusinessPhone($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setLevel($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setPassword($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setSalt($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setCreatedAt($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setUpdatedAt($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setExtra1($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setExtra2($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setExtra3($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setExtra4($arr[$keys[24]]);
		if (array_key_exists($keys[25], $arr)) $this->setExtra5($arr[$keys[25]]);
		if (array_key_exists($keys[26], $arr)) $this->setExtra6($arr[$keys[26]]);
		if (array_key_exists($keys[27], $arr)) $this->setExtra7($arr[$keys[27]]);
		if (array_key_exists($keys[28], $arr)) $this->setExtra8($arr[$keys[28]]);
		if (array_key_exists($keys[29], $arr)) $this->setExtra9($arr[$keys[29]]);
		if (array_key_exists($keys[30], $arr)) $this->setExtra10($arr[$keys[30]]);
		if (array_key_exists($keys[31], $arr)) $this->setExtra11($arr[$keys[31]]);
		if (array_key_exists($keys[32], $arr)) $this->setExtra12($arr[$keys[32]]);
		if (array_key_exists($keys[33], $arr)) $this->setExtra13($arr[$keys[33]]);
		if (array_key_exists($keys[34], $arr)) $this->setExtra14($arr[$keys[34]]);
		if (array_key_exists($keys[35], $arr)) $this->setExtra15($arr[$keys[35]]);
		if (array_key_exists($keys[36], $arr)) $this->setExtra16($arr[$keys[36]]);
		if (array_key_exists($keys[37], $arr)) $this->setExtra17($arr[$keys[37]]);
		if (array_key_exists($keys[38], $arr)) $this->setExtra18($arr[$keys[38]]);
		if (array_key_exists($keys[39], $arr)) $this->setExtra19($arr[$keys[39]]);
		if (array_key_exists($keys[40], $arr)) $this->setExtra20($arr[$keys[40]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(StudentPeer::DATABASE_NAME);

		if ($this->isColumnModified(StudentPeer::ID)) $criteria->add(StudentPeer::ID, $this->id);
		if ($this->isColumnModified(StudentPeer::FMID)) $criteria->add(StudentPeer::FMID, $this->fmid);
		if ($this->isColumnModified(StudentPeer::FIRST_NAME)) $criteria->add(StudentPeer::FIRST_NAME, $this->first_name);
		if ($this->isColumnModified(StudentPeer::LAST_NAME)) $criteria->add(StudentPeer::LAST_NAME, $this->last_name);
		if ($this->isColumnModified(StudentPeer::EMAIL)) $criteria->add(StudentPeer::EMAIL, $this->email);
		if ($this->isColumnModified(StudentPeer::RESET_KEY)) $criteria->add(StudentPeer::RESET_KEY, $this->reset_key);
		if ($this->isColumnModified(StudentPeer::NEW_EMAIL)) $criteria->add(StudentPeer::NEW_EMAIL, $this->new_email);
		if ($this->isColumnModified(StudentPeer::NEW_EMAIL_REQUEST_TIME)) $criteria->add(StudentPeer::NEW_EMAIL_REQUEST_TIME, $this->new_email_request_time);
		if ($this->isColumnModified(StudentPeer::HOME_ADDRESS)) $criteria->add(StudentPeer::HOME_ADDRESS, $this->home_address);
		if ($this->isColumnModified(StudentPeer::CITY)) $criteria->add(StudentPeer::CITY, $this->city);
		if ($this->isColumnModified(StudentPeer::STATE_PROV)) $criteria->add(StudentPeer::STATE_PROV, $this->state_prov);
		if ($this->isColumnModified(StudentPeer::COUNTRY)) $criteria->add(StudentPeer::COUNTRY, $this->country);
		if ($this->isColumnModified(StudentPeer::ZIP_POSTAL)) $criteria->add(StudentPeer::ZIP_POSTAL, $this->zip_postal);
		if ($this->isColumnModified(StudentPeer::HOME_PHONE)) $criteria->add(StudentPeer::HOME_PHONE, $this->home_phone);
		if ($this->isColumnModified(StudentPeer::CELL_PHONE)) $criteria->add(StudentPeer::CELL_PHONE, $this->cell_phone);
		if ($this->isColumnModified(StudentPeer::BUSINESS_PHONE)) $criteria->add(StudentPeer::BUSINESS_PHONE, $this->business_phone);
		if ($this->isColumnModified(StudentPeer::LEVEL)) $criteria->add(StudentPeer::LEVEL, $this->level);
		if ($this->isColumnModified(StudentPeer::PASSWORD)) $criteria->add(StudentPeer::PASSWORD, $this->password);
		if ($this->isColumnModified(StudentPeer::SALT)) $criteria->add(StudentPeer::SALT, $this->salt);
		if ($this->isColumnModified(StudentPeer::CREATED_AT)) $criteria->add(StudentPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(StudentPeer::UPDATED_AT)) $criteria->add(StudentPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(StudentPeer::EXTRA1)) $criteria->add(StudentPeer::EXTRA1, $this->extra1);
		if ($this->isColumnModified(StudentPeer::EXTRA2)) $criteria->add(StudentPeer::EXTRA2, $this->extra2);
		if ($this->isColumnModified(StudentPeer::EXTRA3)) $criteria->add(StudentPeer::EXTRA3, $this->extra3);
		if ($this->isColumnModified(StudentPeer::EXTRA4)) $criteria->add(StudentPeer::EXTRA4, $this->extra4);
		if ($this->isColumnModified(StudentPeer::EXTRA5)) $criteria->add(StudentPeer::EXTRA5, $this->extra5);
		if ($this->isColumnModified(StudentPeer::EXTRA6)) $criteria->add(StudentPeer::EXTRA6, $this->extra6);
		if ($this->isColumnModified(StudentPeer::EXTRA7)) $criteria->add(StudentPeer::EXTRA7, $this->extra7);
		if ($this->isColumnModified(StudentPeer::EXTRA8)) $criteria->add(StudentPeer::EXTRA8, $this->extra8);
		if ($this->isColumnModified(StudentPeer::EXTRA9)) $criteria->add(StudentPeer::EXTRA9, $this->extra9);
		if ($this->isColumnModified(StudentPeer::EXTRA10)) $criteria->add(StudentPeer::EXTRA10, $this->extra10);
		if ($this->isColumnModified(StudentPeer::EXTRA11)) $criteria->add(StudentPeer::EXTRA11, $this->extra11);
		if ($this->isColumnModified(StudentPeer::EXTRA12)) $criteria->add(StudentPeer::EXTRA12, $this->extra12);
		if ($this->isColumnModified(StudentPeer::EXTRA13)) $criteria->add(StudentPeer::EXTRA13, $this->extra13);
		if ($this->isColumnModified(StudentPeer::EXTRA14)) $criteria->add(StudentPeer::EXTRA14, $this->extra14);
		if ($this->isColumnModified(StudentPeer::EXTRA15)) $criteria->add(StudentPeer::EXTRA15, $this->extra15);
		if ($this->isColumnModified(StudentPeer::EXTRA16)) $criteria->add(StudentPeer::EXTRA16, $this->extra16);
		if ($this->isColumnModified(StudentPeer::EXTRA17)) $criteria->add(StudentPeer::EXTRA17, $this->extra17);
		if ($this->isColumnModified(StudentPeer::EXTRA18)) $criteria->add(StudentPeer::EXTRA18, $this->extra18);
		if ($this->isColumnModified(StudentPeer::EXTRA19)) $criteria->add(StudentPeer::EXTRA19, $this->extra19);
		if ($this->isColumnModified(StudentPeer::EXTRA20)) $criteria->add(StudentPeer::EXTRA20, $this->extra20);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(StudentPeer::DATABASE_NAME);

		$criteria->add(StudentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Student (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFmid($this->fmid);

		$copyObj->setFirstName($this->first_name);

		$copyObj->setLastName($this->last_name);

		$copyObj->setEmail($this->email);

		$copyObj->setResetKey($this->reset_key);

		$copyObj->setNewEmail($this->new_email);

		$copyObj->setNewEmailRequestTime($this->new_email_request_time);

		$copyObj->setHomeAddress($this->home_address);

		$copyObj->setCity($this->city);

		$copyObj->setStateProv($this->state_prov);

		$copyObj->setCountry($this->country);

		$copyObj->setZipPostal($this->zip_postal);

		$copyObj->setHomePhone($this->home_phone);

		$copyObj->setCellPhone($this->cell_phone);

		$copyObj->setBusinessPhone($this->business_phone);

		$copyObj->setLevel($this->level);

		$copyObj->setPassword($this->password);

		$copyObj->setSalt($this->salt);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setExtra1($this->extra1);

		$copyObj->setExtra2($this->extra2);

		$copyObj->setExtra3($this->extra3);

		$copyObj->setExtra4($this->extra4);

		$copyObj->setExtra5($this->extra5);

		$copyObj->setExtra6($this->extra6);

		$copyObj->setExtra7($this->extra7);

		$copyObj->setExtra8($this->extra8);

		$copyObj->setExtra9($this->extra9);

		$copyObj->setExtra10($this->extra10);

		$copyObj->setExtra11($this->extra11);

		$copyObj->setExtra12($this->extra12);

		$copyObj->setExtra13($this->extra13);

		$copyObj->setExtra14($this->extra14);

		$copyObj->setExtra15($this->extra15);

		$copyObj->setExtra16($this->extra16);

		$copyObj->setExtra17($this->extra17);

		$copyObj->setExtra18($this->extra18);

		$copyObj->setExtra19($this->extra19);

		$copyObj->setExtra20($this->extra20);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getEnrollments() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addEnrollment($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Student Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     StudentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new StudentPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collEnrollments collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addEnrollments()
	 */
	public function clearEnrollments()
	{
		$this->collEnrollments = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collEnrollments collection (array).
	 *
	 * By default this just sets the collEnrollments collection to an empty array (like clearcollEnrollments());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initEnrollments()
	{
		$this->collEnrollments = array();
	}

	/**
	 * Gets an array of Enrollment objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Student has previously been saved, it will retrieve
	 * related Enrollments from storage. If this Student is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Enrollment[]
	 * @throws     PropelException
	 */
	public function getEnrollments($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEnrollments === null) {
			if ($this->isNew()) {
			   $this->collEnrollments = array();
			} else {

				$criteria->add(EnrollmentPeer::STUDENT_ID, $this->id);

				EnrollmentPeer::addSelectColumns($criteria);
				$this->collEnrollments = EnrollmentPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(EnrollmentPeer::STUDENT_ID, $this->id);

				EnrollmentPeer::addSelectColumns($criteria);
				if (!isset($this->lastEnrollmentCriteria) || !$this->lastEnrollmentCriteria->equals($criteria)) {
					$this->collEnrollments = EnrollmentPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastEnrollmentCriteria = $criteria;
		return $this->collEnrollments;
	}

	/**
	 * Returns the number of related Enrollment objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Enrollment objects.
	 * @throws     PropelException
	 */
	public function countEnrollments(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collEnrollments === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(EnrollmentPeer::STUDENT_ID, $this->id);

				$count = EnrollmentPeer::doCount($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(EnrollmentPeer::STUDENT_ID, $this->id);

				if (!isset($this->lastEnrollmentCriteria) || !$this->lastEnrollmentCriteria->equals($criteria)) {
					$count = EnrollmentPeer::doCount($criteria, $con);
				} else {
					$count = count($this->collEnrollments);
				}
			} else {
				$count = count($this->collEnrollments);
			}
		}
		$this->lastEnrollmentCriteria = $criteria;
		return $count;
	}

	/**
	 * Method called to associate a Enrollment object to this object
	 * through the Enrollment foreign key attribute.
	 *
	 * @param      Enrollment $l Enrollment
	 * @return     void
	 * @throws     PropelException
	 */
	public function addEnrollment(Enrollment $l)
	{
		if ($this->collEnrollments === null) {
			$this->initEnrollments();
		}
		if (!in_array($l, $this->collEnrollments, true)) { // only add it if the **same** object is not already associated
			array_push($this->collEnrollments, $l);
			$l->setStudent($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Student is new, it will return
	 * an empty collection; or if this Student has previously
	 * been saved, it will retrieve related Enrollments from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Student.
	 */
	public function getEnrollmentsJoinEvent($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(StudentPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collEnrollments === null) {
			if ($this->isNew()) {
				$this->collEnrollments = array();
			} else {

				$criteria->add(EnrollmentPeer::STUDENT_ID, $this->id);

				$this->collEnrollments = EnrollmentPeer::doSelectJoinEvent($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(EnrollmentPeer::STUDENT_ID, $this->id);

			if (!isset($this->lastEnrollmentCriteria) || !$this->lastEnrollmentCriteria->equals($criteria)) {
				$this->collEnrollments = EnrollmentPeer::doSelectJoinEvent($criteria, $con, $join_behavior);
			}
		}
		$this->lastEnrollmentCriteria = $criteria;

		return $this->collEnrollments;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collEnrollments) {
				foreach ((array) $this->collEnrollments as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collEnrollments = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseStudent:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseStudent::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseStudent
