<?php

/**
 * Base class that represents a row from the 'enrollment' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov 28 13:47:54 2011
 *
 * @package    lib.model.om
 */
abstract class BaseEnrollment extends BaseObject  implements Persistent {


  const PEER = 'EnrollmentPeer';

	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        EnrollmentPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the student_id field.
	 * @var        int
	 */
	protected $student_id;

	/**
	 * The value for the event_id field.
	 * @var        int
	 */
	protected $event_id;

	/**
	 * The value for the date field.
	 * @var        string
	 */
	protected $date;

	/**
	 * The value for the start_date field.
	 * @var        string
	 */
	protected $start_date;

	/**
	 * The value for the end_date field.
	 * @var        string
	 */
	protected $end_date;

	/**
	 * The value for the type field.
	 * @var        string
	 */
	protected $type;

	/**
	 * The value for the updated_at field.
	 * @var        string
	 */
	protected $updated_at;

	/**
	 * The value for the created_at field.
	 * @var        string
	 */
	protected $created_at;

	/**
	 * The value for the extra1 field.
	 * @var        string
	 */
	protected $extra1;

	/**
	 * The value for the extra2 field.
	 * @var        string
	 */
	protected $extra2;

	/**
	 * The value for the extra3 field.
	 * @var        string
	 */
	protected $extra3;

	/**
	 * The value for the extra4 field.
	 * @var        string
	 */
	protected $extra4;

	/**
	 * The value for the extra5 field.
	 * @var        string
	 */
	protected $extra5;

	/**
	 * The value for the extra6 field.
	 * @var        string
	 */
	protected $extra6;

	/**
	 * The value for the extra7 field.
	 * @var        string
	 */
	protected $extra7;

	/**
	 * The value for the extra8 field.
	 * @var        string
	 */
	protected $extra8;

	/**
	 * The value for the extra9 field.
	 * @var        string
	 */
	protected $extra9;

	/**
	 * The value for the extra10 field.
	 * @var        string
	 */
	protected $extra10;

	/**
	 * The value for the extra11 field.
	 * @var        string
	 */
	protected $extra11;

	/**
	 * The value for the extra12 field.
	 * @var        string
	 */
	protected $extra12;

	/**
	 * The value for the extra13 field.
	 * @var        string
	 */
	protected $extra13;

	/**
	 * The value for the extra14 field.
	 * @var        string
	 */
	protected $extra14;

	/**
	 * The value for the extra15 field.
	 * @var        string
	 */
	protected $extra15;

	/**
	 * The value for the extra16 field.
	 * @var        string
	 */
	protected $extra16;

	/**
	 * The value for the extra17 field.
	 * @var        string
	 */
	protected $extra17;

	/**
	 * The value for the extra18 field.
	 * @var        string
	 */
	protected $extra18;

	/**
	 * The value for the extra19 field.
	 * @var        string
	 */
	protected $extra19;

	/**
	 * The value for the extra20 field.
	 * @var        string
	 */
	protected $extra20;

	/**
	 * @var        Student
	 */
	protected $aStudent;

	/**
	 * @var        Event
	 */
	protected $aEvent;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	/**
	 * Initializes internal state of BaseEnrollment object.
	 * @see        applyDefaults()
	 */
	public function __construct()
	{
		parent::__construct();
		$this->applyDefaultValues();
	}

	/**
	 * Applies default values to this object.
	 * This method should be called from the object's constructor (or
	 * equivalent initialization method).
	 * @see        __construct()
	 */
	public function applyDefaultValues()
	{
	}

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [student_id] column value.
	 * 
	 * @return     int
	 */
	public function getStudentId()
	{
		return $this->student_id;
	}

	/**
	 * Get the [event_id] column value.
	 * 
	 * @return     int
	 */
	public function getEventId()
	{
		return $this->event_id;
	}

	/**
	 * Get the [optionally formatted] temporal [date] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDate($format = 'Y-m-d H:i:s')
	{
		if ($this->date === null) {
			return null;
		}


		if ($this->date === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [start_date] column value.
	 * 
	 * @return     string
	 */
	public function getStartDate()
	{
		return $this->start_date;
	}

	/**
	 * Get the [end_date] column value.
	 * 
	 * @return     string
	 */
	public function getEndDate()
	{
		return $this->end_date;
	}

	/**
	 * Get the [type] column value.
	 * 
	 * @return     string
	 */
	public function getType()
	{
		return $this->type;
	}

	/**
	 * Get the [optionally formatted] temporal [updated_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getUpdatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->updated_at === null) {
			return null;
		}


		if ($this->updated_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->updated_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->updated_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [created_at] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getCreatedAt($format = 'Y-m-d H:i:s')
	{
		if ($this->created_at === null) {
			return null;
		}


		if ($this->created_at === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->created_at);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->created_at, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [extra1] column value.
	 * 
	 * @return     string
	 */
	public function getExtra1()
	{
		return $this->extra1;
	}

	/**
	 * Get the [extra2] column value.
	 * 
	 * @return     string
	 */
	public function getExtra2()
	{
		return $this->extra2;
	}

	/**
	 * Get the [extra3] column value.
	 * 
	 * @return     string
	 */
	public function getExtra3()
	{
		return $this->extra3;
	}

	/**
	 * Get the [extra4] column value.
	 * 
	 * @return     string
	 */
	public function getExtra4()
	{
		return $this->extra4;
	}

	/**
	 * Get the [extra5] column value.
	 * 
	 * @return     string
	 */
	public function getExtra5()
	{
		return $this->extra5;
	}

	/**
	 * Get the [extra6] column value.
	 * 
	 * @return     string
	 */
	public function getExtra6()
	{
		return $this->extra6;
	}

	/**
	 * Get the [extra7] column value.
	 * 
	 * @return     string
	 */
	public function getExtra7()
	{
		return $this->extra7;
	}

	/**
	 * Get the [extra8] column value.
	 * 
	 * @return     string
	 */
	public function getExtra8()
	{
		return $this->extra8;
	}

	/**
	 * Get the [extra9] column value.
	 * 
	 * @return     string
	 */
	public function getExtra9()
	{
		return $this->extra9;
	}

	/**
	 * Get the [extra10] column value.
	 * 
	 * @return     string
	 */
	public function getExtra10()
	{
		return $this->extra10;
	}

	/**
	 * Get the [extra11] column value.
	 * 
	 * @return     string
	 */
	public function getExtra11()
	{
		return $this->extra11;
	}

	/**
	 * Get the [extra12] column value.
	 * 
	 * @return     string
	 */
	public function getExtra12()
	{
		return $this->extra12;
	}

	/**
	 * Get the [extra13] column value.
	 * 
	 * @return     string
	 */
	public function getExtra13()
	{
		return $this->extra13;
	}

	/**
	 * Get the [extra14] column value.
	 * 
	 * @return     string
	 */
	public function getExtra14()
	{
		return $this->extra14;
	}

	/**
	 * Get the [extra15] column value.
	 * 
	 * @return     string
	 */
	public function getExtra15()
	{
		return $this->extra15;
	}

	/**
	 * Get the [extra16] column value.
	 * 
	 * @return     string
	 */
	public function getExtra16()
	{
		return $this->extra16;
	}

	/**
	 * Get the [extra17] column value.
	 * 
	 * @return     string
	 */
	public function getExtra17()
	{
		return $this->extra17;
	}

	/**
	 * Get the [extra18] column value.
	 * 
	 * @return     string
	 */
	public function getExtra18()
	{
		return $this->extra18;
	}

	/**
	 * Get the [extra19] column value.
	 * 
	 * @return     string
	 */
	public function getExtra19()
	{
		return $this->extra19;
	}

	/**
	 * Get the [extra20] column value.
	 * 
	 * @return     string
	 */
	public function getExtra20()
	{
		return $this->extra20;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = EnrollmentPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [student_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setStudentId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->student_id !== $v) {
			$this->student_id = $v;
			$this->modifiedColumns[] = EnrollmentPeer::STUDENT_ID;
		}

		if ($this->aStudent !== null && $this->aStudent->getId() !== $v) {
			$this->aStudent = null;
		}

		return $this;
	} // setStudentId()

	/**
	 * Set the value of [event_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setEventId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->event_id !== $v) {
			$this->event_id = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EVENT_ID;
		}

		if ($this->aEvent !== null && $this->aEvent->getId() !== $v) {
			$this->aEvent = null;
		}

		return $this;
	} // setEventId()

	/**
	 * Sets the value of [date] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setDate($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date !== null && $tmpDt = new DateTime($this->date)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EnrollmentPeer::DATE;
			}
		} // if either are not null

		return $this;
	} // setDate()

	/**
	 * Set the value of [start_date] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setStartDate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->start_date !== $v) {
			$this->start_date = $v;
			$this->modifiedColumns[] = EnrollmentPeer::START_DATE;
		}

		return $this;
	} // setStartDate()

	/**
	 * Set the value of [end_date] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setEndDate($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->end_date !== $v) {
			$this->end_date = $v;
			$this->modifiedColumns[] = EnrollmentPeer::END_DATE;
		}

		return $this;
	} // setEndDate()

	/**
	 * Set the value of [type] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setType($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->type !== $v) {
			$this->type = $v;
			$this->modifiedColumns[] = EnrollmentPeer::TYPE;
		}

		return $this;
	} // setType()

	/**
	 * Sets the value of [updated_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setUpdatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->updated_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->updated_at !== null && $tmpDt = new DateTime($this->updated_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->updated_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EnrollmentPeer::UPDATED_AT;
			}
		} // if either are not null

		return $this;
	} // setUpdatedAt()

	/**
	 * Sets the value of [created_at] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setCreatedAt($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->created_at !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->created_at !== null && $tmpDt = new DateTime($this->created_at)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->created_at = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = EnrollmentPeer::CREATED_AT;
			}
		} // if either are not null

		return $this;
	} // setCreatedAt()

	/**
	 * Set the value of [extra1] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra1($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra1 !== $v) {
			$this->extra1 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA1;
		}

		return $this;
	} // setExtra1()

	/**
	 * Set the value of [extra2] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra2($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra2 !== $v) {
			$this->extra2 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA2;
		}

		return $this;
	} // setExtra2()

	/**
	 * Set the value of [extra3] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra3($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra3 !== $v) {
			$this->extra3 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA3;
		}

		return $this;
	} // setExtra3()

	/**
	 * Set the value of [extra4] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra4($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra4 !== $v) {
			$this->extra4 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA4;
		}

		return $this;
	} // setExtra4()

	/**
	 * Set the value of [extra5] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra5($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra5 !== $v) {
			$this->extra5 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA5;
		}

		return $this;
	} // setExtra5()

	/**
	 * Set the value of [extra6] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra6($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra6 !== $v) {
			$this->extra6 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA6;
		}

		return $this;
	} // setExtra6()

	/**
	 * Set the value of [extra7] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra7($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra7 !== $v) {
			$this->extra7 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA7;
		}

		return $this;
	} // setExtra7()

	/**
	 * Set the value of [extra8] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra8($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra8 !== $v) {
			$this->extra8 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA8;
		}

		return $this;
	} // setExtra8()

	/**
	 * Set the value of [extra9] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra9($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra9 !== $v) {
			$this->extra9 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA9;
		}

		return $this;
	} // setExtra9()

	/**
	 * Set the value of [extra10] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra10($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra10 !== $v) {
			$this->extra10 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA10;
		}

		return $this;
	} // setExtra10()

	/**
	 * Set the value of [extra11] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra11($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra11 !== $v) {
			$this->extra11 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA11;
		}

		return $this;
	} // setExtra11()

	/**
	 * Set the value of [extra12] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra12($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra12 !== $v) {
			$this->extra12 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA12;
		}

		return $this;
	} // setExtra12()

	/**
	 * Set the value of [extra13] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra13($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra13 !== $v) {
			$this->extra13 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA13;
		}

		return $this;
	} // setExtra13()

	/**
	 * Set the value of [extra14] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra14($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra14 !== $v) {
			$this->extra14 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA14;
		}

		return $this;
	} // setExtra14()

	/**
	 * Set the value of [extra15] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra15($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra15 !== $v) {
			$this->extra15 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA15;
		}

		return $this;
	} // setExtra15()

	/**
	 * Set the value of [extra16] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra16($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra16 !== $v) {
			$this->extra16 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA16;
		}

		return $this;
	} // setExtra16()

	/**
	 * Set the value of [extra17] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra17($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra17 !== $v) {
			$this->extra17 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA17;
		}

		return $this;
	} // setExtra17()

	/**
	 * Set the value of [extra18] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra18($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra18 !== $v) {
			$this->extra18 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA18;
		}

		return $this;
	} // setExtra18()

	/**
	 * Set the value of [extra19] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra19($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra19 !== $v) {
			$this->extra19 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA19;
		}

		return $this;
	} // setExtra19()

	/**
	 * Set the value of [extra20] column.
	 * 
	 * @param      string $v new value
	 * @return     Enrollment The current object (for fluent API support)
	 */
	public function setExtra20($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->extra20 !== $v) {
			$this->extra20 = $v;
			$this->modifiedColumns[] = EnrollmentPeer::EXTRA20;
		}

		return $this;
	} // setExtra20()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
			// First, ensure that we don't have any columns that have been modified which aren't default columns.
			if (array_diff($this->modifiedColumns, array())) {
				return false;
			}

		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->student_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->event_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->date = ($row[$startcol + 3] !== null) ? (string) $row[$startcol + 3] : null;
			$this->start_date = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->end_date = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->type = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->updated_at = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->created_at = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->extra1 = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->extra2 = ($row[$startcol + 10] !== null) ? (string) $row[$startcol + 10] : null;
			$this->extra3 = ($row[$startcol + 11] !== null) ? (string) $row[$startcol + 11] : null;
			$this->extra4 = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->extra5 = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->extra6 = ($row[$startcol + 14] !== null) ? (string) $row[$startcol + 14] : null;
			$this->extra7 = ($row[$startcol + 15] !== null) ? (string) $row[$startcol + 15] : null;
			$this->extra8 = ($row[$startcol + 16] !== null) ? (string) $row[$startcol + 16] : null;
			$this->extra9 = ($row[$startcol + 17] !== null) ? (string) $row[$startcol + 17] : null;
			$this->extra10 = ($row[$startcol + 18] !== null) ? (string) $row[$startcol + 18] : null;
			$this->extra11 = ($row[$startcol + 19] !== null) ? (string) $row[$startcol + 19] : null;
			$this->extra12 = ($row[$startcol + 20] !== null) ? (string) $row[$startcol + 20] : null;
			$this->extra13 = ($row[$startcol + 21] !== null) ? (string) $row[$startcol + 21] : null;
			$this->extra14 = ($row[$startcol + 22] !== null) ? (string) $row[$startcol + 22] : null;
			$this->extra15 = ($row[$startcol + 23] !== null) ? (string) $row[$startcol + 23] : null;
			$this->extra16 = ($row[$startcol + 24] !== null) ? (string) $row[$startcol + 24] : null;
			$this->extra17 = ($row[$startcol + 25] !== null) ? (string) $row[$startcol + 25] : null;
			$this->extra18 = ($row[$startcol + 26] !== null) ? (string) $row[$startcol + 26] : null;
			$this->extra19 = ($row[$startcol + 27] !== null) ? (string) $row[$startcol + 27] : null;
			$this->extra20 = ($row[$startcol + 28] !== null) ? (string) $row[$startcol + 28] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 29; // 29 = EnrollmentPeer::NUM_COLUMNS - EnrollmentPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Enrollment object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aStudent !== null && $this->student_id !== $this->aStudent->getId()) {
			$this->aStudent = null;
		}
		if ($this->aEvent !== null && $this->event_id !== $this->aEvent->getId()) {
			$this->aEvent = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EnrollmentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = EnrollmentPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aStudent = null;
			$this->aEvent = null;
		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEnrollment:delete:pre') as $callable)
    {
      $ret = call_user_func($callable, $this, $con);
      if ($ret)
      {
        return;
      }
    }


		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EnrollmentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			EnrollmentPeer::doDelete($this, $con);
			$this->setDeleted(true);
			$con->commit();
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	

    foreach (sfMixer::getCallables('BaseEnrollment:delete:post') as $callable)
    {
      call_user_func($callable, $this, $con);
    }

  }
	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEnrollment:save:pre') as $callable)
    {
      $affectedRows = call_user_func($callable, $this, $con);
      if (is_int($affectedRows))
      {
        return $affectedRows;
      }
    }


    if ($this->isModified() && !$this->isColumnModified(EnrollmentPeer::UPDATED_AT))
    {
      $this->setUpdatedAt(time());
    }

    if ($this->isNew() && !$this->isColumnModified(EnrollmentPeer::CREATED_AT))
    {
      $this->setCreatedAt(time());
    }

		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(EnrollmentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$affectedRows = $this->doSave($con);
			$con->commit();
    foreach (sfMixer::getCallables('BaseEnrollment:save:post') as $callable)
    {
      call_user_func($callable, $this, $con, $affectedRows);
    }

			EnrollmentPeer::addInstanceToPool($this);
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudent !== null) {
				if ($this->aStudent->isModified() || $this->aStudent->isNew()) {
					$affectedRows += $this->aStudent->save($con);
				}
				$this->setStudent($this->aStudent);
			}

			if ($this->aEvent !== null) {
				if ($this->aEvent->isModified() || $this->aEvent->isNew()) {
					$affectedRows += $this->aEvent->save($con);
				}
				$this->setEvent($this->aEvent);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = EnrollmentPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = EnrollmentPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += EnrollmentPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aStudent !== null) {
				if (!$this->aStudent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aStudent->getValidationFailures());
				}
			}

			if ($this->aEvent !== null) {
				if (!$this->aEvent->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aEvent->getValidationFailures());
				}
			}


			if (($retval = EnrollmentPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}



			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EnrollmentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getStudentId();
				break;
			case 2:
				return $this->getEventId();
				break;
			case 3:
				return $this->getDate();
				break;
			case 4:
				return $this->getStartDate();
				break;
			case 5:
				return $this->getEndDate();
				break;
			case 6:
				return $this->getType();
				break;
			case 7:
				return $this->getUpdatedAt();
				break;
			case 8:
				return $this->getCreatedAt();
				break;
			case 9:
				return $this->getExtra1();
				break;
			case 10:
				return $this->getExtra2();
				break;
			case 11:
				return $this->getExtra3();
				break;
			case 12:
				return $this->getExtra4();
				break;
			case 13:
				return $this->getExtra5();
				break;
			case 14:
				return $this->getExtra6();
				break;
			case 15:
				return $this->getExtra7();
				break;
			case 16:
				return $this->getExtra8();
				break;
			case 17:
				return $this->getExtra9();
				break;
			case 18:
				return $this->getExtra10();
				break;
			case 19:
				return $this->getExtra11();
				break;
			case 20:
				return $this->getExtra12();
				break;
			case 21:
				return $this->getExtra13();
				break;
			case 22:
				return $this->getExtra14();
				break;
			case 23:
				return $this->getExtra15();
				break;
			case 24:
				return $this->getExtra16();
				break;
			case 25:
				return $this->getExtra17();
				break;
			case 26:
				return $this->getExtra18();
				break;
			case 27:
				return $this->getExtra19();
				break;
			case 28:
				return $this->getExtra20();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = EnrollmentPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getStudentId(),
			$keys[2] => $this->getEventId(),
			$keys[3] => $this->getDate(),
			$keys[4] => $this->getStartDate(),
			$keys[5] => $this->getEndDate(),
			$keys[6] => $this->getType(),
			$keys[7] => $this->getUpdatedAt(),
			$keys[8] => $this->getCreatedAt(),
			$keys[9] => $this->getExtra1(),
			$keys[10] => $this->getExtra2(),
			$keys[11] => $this->getExtra3(),
			$keys[12] => $this->getExtra4(),
			$keys[13] => $this->getExtra5(),
			$keys[14] => $this->getExtra6(),
			$keys[15] => $this->getExtra7(),
			$keys[16] => $this->getExtra8(),
			$keys[17] => $this->getExtra9(),
			$keys[18] => $this->getExtra10(),
			$keys[19] => $this->getExtra11(),
			$keys[20] => $this->getExtra12(),
			$keys[21] => $this->getExtra13(),
			$keys[22] => $this->getExtra14(),
			$keys[23] => $this->getExtra15(),
			$keys[24] => $this->getExtra16(),
			$keys[25] => $this->getExtra17(),
			$keys[26] => $this->getExtra18(),
			$keys[27] => $this->getExtra19(),
			$keys[28] => $this->getExtra20(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = EnrollmentPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setStudentId($value);
				break;
			case 2:
				$this->setEventId($value);
				break;
			case 3:
				$this->setDate($value);
				break;
			case 4:
				$this->setStartDate($value);
				break;
			case 5:
				$this->setEndDate($value);
				break;
			case 6:
				$this->setType($value);
				break;
			case 7:
				$this->setUpdatedAt($value);
				break;
			case 8:
				$this->setCreatedAt($value);
				break;
			case 9:
				$this->setExtra1($value);
				break;
			case 10:
				$this->setExtra2($value);
				break;
			case 11:
				$this->setExtra3($value);
				break;
			case 12:
				$this->setExtra4($value);
				break;
			case 13:
				$this->setExtra5($value);
				break;
			case 14:
				$this->setExtra6($value);
				break;
			case 15:
				$this->setExtra7($value);
				break;
			case 16:
				$this->setExtra8($value);
				break;
			case 17:
				$this->setExtra9($value);
				break;
			case 18:
				$this->setExtra10($value);
				break;
			case 19:
				$this->setExtra11($value);
				break;
			case 20:
				$this->setExtra12($value);
				break;
			case 21:
				$this->setExtra13($value);
				break;
			case 22:
				$this->setExtra14($value);
				break;
			case 23:
				$this->setExtra15($value);
				break;
			case 24:
				$this->setExtra16($value);
				break;
			case 25:
				$this->setExtra17($value);
				break;
			case 26:
				$this->setExtra18($value);
				break;
			case 27:
				$this->setExtra19($value);
				break;
			case 28:
				$this->setExtra20($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = EnrollmentPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setStudentId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setEventId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setDate($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setStartDate($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setEndDate($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setType($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setUpdatedAt($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setCreatedAt($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setExtra1($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setExtra2($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setExtra3($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setExtra4($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setExtra5($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setExtra6($arr[$keys[14]]);
		if (array_key_exists($keys[15], $arr)) $this->setExtra7($arr[$keys[15]]);
		if (array_key_exists($keys[16], $arr)) $this->setExtra8($arr[$keys[16]]);
		if (array_key_exists($keys[17], $arr)) $this->setExtra9($arr[$keys[17]]);
		if (array_key_exists($keys[18], $arr)) $this->setExtra10($arr[$keys[18]]);
		if (array_key_exists($keys[19], $arr)) $this->setExtra11($arr[$keys[19]]);
		if (array_key_exists($keys[20], $arr)) $this->setExtra12($arr[$keys[20]]);
		if (array_key_exists($keys[21], $arr)) $this->setExtra13($arr[$keys[21]]);
		if (array_key_exists($keys[22], $arr)) $this->setExtra14($arr[$keys[22]]);
		if (array_key_exists($keys[23], $arr)) $this->setExtra15($arr[$keys[23]]);
		if (array_key_exists($keys[24], $arr)) $this->setExtra16($arr[$keys[24]]);
		if (array_key_exists($keys[25], $arr)) $this->setExtra17($arr[$keys[25]]);
		if (array_key_exists($keys[26], $arr)) $this->setExtra18($arr[$keys[26]]);
		if (array_key_exists($keys[27], $arr)) $this->setExtra19($arr[$keys[27]]);
		if (array_key_exists($keys[28], $arr)) $this->setExtra20($arr[$keys[28]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(EnrollmentPeer::DATABASE_NAME);

		if ($this->isColumnModified(EnrollmentPeer::ID)) $criteria->add(EnrollmentPeer::ID, $this->id);
		if ($this->isColumnModified(EnrollmentPeer::STUDENT_ID)) $criteria->add(EnrollmentPeer::STUDENT_ID, $this->student_id);
		if ($this->isColumnModified(EnrollmentPeer::EVENT_ID)) $criteria->add(EnrollmentPeer::EVENT_ID, $this->event_id);
		if ($this->isColumnModified(EnrollmentPeer::DATE)) $criteria->add(EnrollmentPeer::DATE, $this->date);
		if ($this->isColumnModified(EnrollmentPeer::START_DATE)) $criteria->add(EnrollmentPeer::START_DATE, $this->start_date);
		if ($this->isColumnModified(EnrollmentPeer::END_DATE)) $criteria->add(EnrollmentPeer::END_DATE, $this->end_date);
		if ($this->isColumnModified(EnrollmentPeer::TYPE)) $criteria->add(EnrollmentPeer::TYPE, $this->type);
		if ($this->isColumnModified(EnrollmentPeer::UPDATED_AT)) $criteria->add(EnrollmentPeer::UPDATED_AT, $this->updated_at);
		if ($this->isColumnModified(EnrollmentPeer::CREATED_AT)) $criteria->add(EnrollmentPeer::CREATED_AT, $this->created_at);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA1)) $criteria->add(EnrollmentPeer::EXTRA1, $this->extra1);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA2)) $criteria->add(EnrollmentPeer::EXTRA2, $this->extra2);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA3)) $criteria->add(EnrollmentPeer::EXTRA3, $this->extra3);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA4)) $criteria->add(EnrollmentPeer::EXTRA4, $this->extra4);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA5)) $criteria->add(EnrollmentPeer::EXTRA5, $this->extra5);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA6)) $criteria->add(EnrollmentPeer::EXTRA6, $this->extra6);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA7)) $criteria->add(EnrollmentPeer::EXTRA7, $this->extra7);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA8)) $criteria->add(EnrollmentPeer::EXTRA8, $this->extra8);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA9)) $criteria->add(EnrollmentPeer::EXTRA9, $this->extra9);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA10)) $criteria->add(EnrollmentPeer::EXTRA10, $this->extra10);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA11)) $criteria->add(EnrollmentPeer::EXTRA11, $this->extra11);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA12)) $criteria->add(EnrollmentPeer::EXTRA12, $this->extra12);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA13)) $criteria->add(EnrollmentPeer::EXTRA13, $this->extra13);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA14)) $criteria->add(EnrollmentPeer::EXTRA14, $this->extra14);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA15)) $criteria->add(EnrollmentPeer::EXTRA15, $this->extra15);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA16)) $criteria->add(EnrollmentPeer::EXTRA16, $this->extra16);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA17)) $criteria->add(EnrollmentPeer::EXTRA17, $this->extra17);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA18)) $criteria->add(EnrollmentPeer::EXTRA18, $this->extra18);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA19)) $criteria->add(EnrollmentPeer::EXTRA19, $this->extra19);
		if ($this->isColumnModified(EnrollmentPeer::EXTRA20)) $criteria->add(EnrollmentPeer::EXTRA20, $this->extra20);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(EnrollmentPeer::DATABASE_NAME);

		$criteria->add(EnrollmentPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Enrollment (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setStudentId($this->student_id);

		$copyObj->setEventId($this->event_id);

		$copyObj->setDate($this->date);

		$copyObj->setStartDate($this->start_date);

		$copyObj->setEndDate($this->end_date);

		$copyObj->setType($this->type);

		$copyObj->setUpdatedAt($this->updated_at);

		$copyObj->setCreatedAt($this->created_at);

		$copyObj->setExtra1($this->extra1);

		$copyObj->setExtra2($this->extra2);

		$copyObj->setExtra3($this->extra3);

		$copyObj->setExtra4($this->extra4);

		$copyObj->setExtra5($this->extra5);

		$copyObj->setExtra6($this->extra6);

		$copyObj->setExtra7($this->extra7);

		$copyObj->setExtra8($this->extra8);

		$copyObj->setExtra9($this->extra9);

		$copyObj->setExtra10($this->extra10);

		$copyObj->setExtra11($this->extra11);

		$copyObj->setExtra12($this->extra12);

		$copyObj->setExtra13($this->extra13);

		$copyObj->setExtra14($this->extra14);

		$copyObj->setExtra15($this->extra15);

		$copyObj->setExtra16($this->extra16);

		$copyObj->setExtra17($this->extra17);

		$copyObj->setExtra18($this->extra18);

		$copyObj->setExtra19($this->extra19);

		$copyObj->setExtra20($this->extra20);


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Enrollment Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     EnrollmentPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new EnrollmentPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Student object.
	 *
	 * @param      Student $v
	 * @return     Enrollment The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setStudent(Student $v = null)
	{
		if ($v === null) {
			$this->setStudentId(NULL);
		} else {
			$this->setStudentId($v->getId());
		}

		$this->aStudent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Student object, it will not be re-added.
		if ($v !== null) {
			$v->addEnrollment($this);
		}

		return $this;
	}


	/**
	 * Get the associated Student object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Student The associated Student object.
	 * @throws     PropelException
	 */
	public function getStudent(PropelPDO $con = null)
	{
		if ($this->aStudent === null && ($this->student_id !== null)) {
			$c = new Criteria(StudentPeer::DATABASE_NAME);
			$c->add(StudentPeer::ID, $this->student_id);
			$this->aStudent = StudentPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aStudent->addEnrollments($this);
			 */
		}
		return $this->aStudent;
	}

	/**
	 * Declares an association between this object and a Event object.
	 *
	 * @param      Event $v
	 * @return     Enrollment The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setEvent(Event $v = null)
	{
		if ($v === null) {
			$this->setEventId(NULL);
		} else {
			$this->setEventId($v->getId());
		}

		$this->aEvent = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Event object, it will not be re-added.
		if ($v !== null) {
			$v->addEnrollment($this);
		}

		return $this;
	}


	/**
	 * Get the associated Event object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Event The associated Event object.
	 * @throws     PropelException
	 */
	public function getEvent(PropelPDO $con = null)
	{
		if ($this->aEvent === null && ($this->event_id !== null)) {
			$c = new Criteria(EventPeer::DATABASE_NAME);
			$c->add(EventPeer::ID, $this->event_id);
			$this->aEvent = EventPeer::doSelectOne($c, $con);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aEvent->addEnrollments($this);
			 */
		}
		return $this->aEvent;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
		} // if ($deep)

			$this->aStudent = null;
			$this->aEvent = null;
	}


  public function __call($method, $arguments)
  {
    if (!$callable = sfMixer::getCallable('BaseEnrollment:'.$method))
    {
      throw new sfException(sprintf('Call to undefined method BaseEnrollment::%s', $method));
    }

    array_unshift($arguments, $this);

    return call_user_func_array($callable, $arguments);
  }


} // BaseEnrollment
