<?php

/**
 * Base static class for performing query and update operations on the 'student' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov 28 13:47:53 2011
 *
 * @package    lib.model.om
 */
abstract class BaseStudentPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'student';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Student';

	/** The total number of columns. */
	const NUM_COLUMNS = 41;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'student.ID';

	/** the column name for the FMID field */
	const FMID = 'student.FMID';

	/** the column name for the FIRST_NAME field */
	const FIRST_NAME = 'student.FIRST_NAME';

	/** the column name for the LAST_NAME field */
	const LAST_NAME = 'student.LAST_NAME';

	/** the column name for the EMAIL field */
	const EMAIL = 'student.EMAIL';

	/** the column name for the RESET_KEY field */
	const RESET_KEY = 'student.RESET_KEY';

	/** the column name for the NEW_EMAIL field */
	const NEW_EMAIL = 'student.NEW_EMAIL';

	/** the column name for the NEW_EMAIL_REQUEST_TIME field */
	const NEW_EMAIL_REQUEST_TIME = 'student.NEW_EMAIL_REQUEST_TIME';

	/** the column name for the HOME_ADDRESS field */
	const HOME_ADDRESS = 'student.HOME_ADDRESS';

	/** the column name for the CITY field */
	const CITY = 'student.CITY';

	/** the column name for the STATE_PROV field */
	const STATE_PROV = 'student.STATE_PROV';

	/** the column name for the COUNTRY field */
	const COUNTRY = 'student.COUNTRY';

	/** the column name for the ZIP_POSTAL field */
	const ZIP_POSTAL = 'student.ZIP_POSTAL';

	/** the column name for the HOME_PHONE field */
	const HOME_PHONE = 'student.HOME_PHONE';

	/** the column name for the CELL_PHONE field */
	const CELL_PHONE = 'student.CELL_PHONE';

	/** the column name for the BUSINESS_PHONE field */
	const BUSINESS_PHONE = 'student.BUSINESS_PHONE';

	/** the column name for the LEVEL field */
	const LEVEL = 'student.LEVEL';

	/** the column name for the PASSWORD field */
	const PASSWORD = 'student.PASSWORD';

	/** the column name for the SALT field */
	const SALT = 'student.SALT';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'student.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'student.UPDATED_AT';

	/** the column name for the EXTRA1 field */
	const EXTRA1 = 'student.EXTRA1';

	/** the column name for the EXTRA2 field */
	const EXTRA2 = 'student.EXTRA2';

	/** the column name for the EXTRA3 field */
	const EXTRA3 = 'student.EXTRA3';

	/** the column name for the EXTRA4 field */
	const EXTRA4 = 'student.EXTRA4';

	/** the column name for the EXTRA5 field */
	const EXTRA5 = 'student.EXTRA5';

	/** the column name for the EXTRA6 field */
	const EXTRA6 = 'student.EXTRA6';

	/** the column name for the EXTRA7 field */
	const EXTRA7 = 'student.EXTRA7';

	/** the column name for the EXTRA8 field */
	const EXTRA8 = 'student.EXTRA8';

	/** the column name for the EXTRA9 field */
	const EXTRA9 = 'student.EXTRA9';

	/** the column name for the EXTRA10 field */
	const EXTRA10 = 'student.EXTRA10';

	/** the column name for the EXTRA11 field */
	const EXTRA11 = 'student.EXTRA11';

	/** the column name for the EXTRA12 field */
	const EXTRA12 = 'student.EXTRA12';

	/** the column name for the EXTRA13 field */
	const EXTRA13 = 'student.EXTRA13';

	/** the column name for the EXTRA14 field */
	const EXTRA14 = 'student.EXTRA14';

	/** the column name for the EXTRA15 field */
	const EXTRA15 = 'student.EXTRA15';

	/** the column name for the EXTRA16 field */
	const EXTRA16 = 'student.EXTRA16';

	/** the column name for the EXTRA17 field */
	const EXTRA17 = 'student.EXTRA17';

	/** the column name for the EXTRA18 field */
	const EXTRA18 = 'student.EXTRA18';

	/** the column name for the EXTRA19 field */
	const EXTRA19 = 'student.EXTRA19';

	/** the column name for the EXTRA20 field */
	const EXTRA20 = 'student.EXTRA20';

	/**
	 * An identiy map to hold any loaded instances of Student objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Student[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Fmid', 'FirstName', 'LastName', 'Email', 'ResetKey', 'NewEmail', 'NewEmailRequestTime', 'HomeAddress', 'City', 'StateProv', 'Country', 'ZipPostal', 'HomePhone', 'CellPhone', 'BusinessPhone', 'Level', 'Password', 'Salt', 'CreatedAt', 'UpdatedAt', 'Extra1', 'Extra2', 'Extra3', 'Extra4', 'Extra5', 'Extra6', 'Extra7', 'Extra8', 'Extra9', 'Extra10', 'Extra11', 'Extra12', 'Extra13', 'Extra14', 'Extra15', 'Extra16', 'Extra17', 'Extra18', 'Extra19', 'Extra20', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'fmid', 'firstName', 'lastName', 'email', 'resetKey', 'newEmail', 'newEmailRequestTime', 'homeAddress', 'city', 'stateProv', 'country', 'zipPostal', 'homePhone', 'cellPhone', 'businessPhone', 'level', 'password', 'salt', 'createdAt', 'updatedAt', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::FMID, self::FIRST_NAME, self::LAST_NAME, self::EMAIL, self::RESET_KEY, self::NEW_EMAIL, self::NEW_EMAIL_REQUEST_TIME, self::HOME_ADDRESS, self::CITY, self::STATE_PROV, self::COUNTRY, self::ZIP_POSTAL, self::HOME_PHONE, self::CELL_PHONE, self::BUSINESS_PHONE, self::LEVEL, self::PASSWORD, self::SALT, self::CREATED_AT, self::UPDATED_AT, self::EXTRA1, self::EXTRA2, self::EXTRA3, self::EXTRA4, self::EXTRA5, self::EXTRA6, self::EXTRA7, self::EXTRA8, self::EXTRA9, self::EXTRA10, self::EXTRA11, self::EXTRA12, self::EXTRA13, self::EXTRA14, self::EXTRA15, self::EXTRA16, self::EXTRA17, self::EXTRA18, self::EXTRA19, self::EXTRA20, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'fmid', 'first_name', 'last_name', 'email', 'reset_key', 'new_email', 'new_email_request_time', 'home_address', 'city', 'state_prov', 'country', 'zip_postal', 'home_phone', 'cell_phone', 'business_phone', 'level', 'password', 'salt', 'created_at', 'updated_at', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Fmid' => 1, 'FirstName' => 2, 'LastName' => 3, 'Email' => 4, 'ResetKey' => 5, 'NewEmail' => 6, 'NewEmailRequestTime' => 7, 'HomeAddress' => 8, 'City' => 9, 'StateProv' => 10, 'Country' => 11, 'ZipPostal' => 12, 'HomePhone' => 13, 'CellPhone' => 14, 'BusinessPhone' => 15, 'Level' => 16, 'Password' => 17, 'Salt' => 18, 'CreatedAt' => 19, 'UpdatedAt' => 20, 'Extra1' => 21, 'Extra2' => 22, 'Extra3' => 23, 'Extra4' => 24, 'Extra5' => 25, 'Extra6' => 26, 'Extra7' => 27, 'Extra8' => 28, 'Extra9' => 29, 'Extra10' => 30, 'Extra11' => 31, 'Extra12' => 32, 'Extra13' => 33, 'Extra14' => 34, 'Extra15' => 35, 'Extra16' => 36, 'Extra17' => 37, 'Extra18' => 38, 'Extra19' => 39, 'Extra20' => 40, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'fmid' => 1, 'firstName' => 2, 'lastName' => 3, 'email' => 4, 'resetKey' => 5, 'newEmail' => 6, 'newEmailRequestTime' => 7, 'homeAddress' => 8, 'city' => 9, 'stateProv' => 10, 'country' => 11, 'zipPostal' => 12, 'homePhone' => 13, 'cellPhone' => 14, 'businessPhone' => 15, 'level' => 16, 'password' => 17, 'salt' => 18, 'createdAt' => 19, 'updatedAt' => 20, 'extra1' => 21, 'extra2' => 22, 'extra3' => 23, 'extra4' => 24, 'extra5' => 25, 'extra6' => 26, 'extra7' => 27, 'extra8' => 28, 'extra9' => 29, 'extra10' => 30, 'extra11' => 31, 'extra12' => 32, 'extra13' => 33, 'extra14' => 34, 'extra15' => 35, 'extra16' => 36, 'extra17' => 37, 'extra18' => 38, 'extra19' => 39, 'extra20' => 40, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::FMID => 1, self::FIRST_NAME => 2, self::LAST_NAME => 3, self::EMAIL => 4, self::RESET_KEY => 5, self::NEW_EMAIL => 6, self::NEW_EMAIL_REQUEST_TIME => 7, self::HOME_ADDRESS => 8, self::CITY => 9, self::STATE_PROV => 10, self::COUNTRY => 11, self::ZIP_POSTAL => 12, self::HOME_PHONE => 13, self::CELL_PHONE => 14, self::BUSINESS_PHONE => 15, self::LEVEL => 16, self::PASSWORD => 17, self::SALT => 18, self::CREATED_AT => 19, self::UPDATED_AT => 20, self::EXTRA1 => 21, self::EXTRA2 => 22, self::EXTRA3 => 23, self::EXTRA4 => 24, self::EXTRA5 => 25, self::EXTRA6 => 26, self::EXTRA7 => 27, self::EXTRA8 => 28, self::EXTRA9 => 29, self::EXTRA10 => 30, self::EXTRA11 => 31, self::EXTRA12 => 32, self::EXTRA13 => 33, self::EXTRA14 => 34, self::EXTRA15 => 35, self::EXTRA16 => 36, self::EXTRA17 => 37, self::EXTRA18 => 38, self::EXTRA19 => 39, self::EXTRA20 => 40, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'fmid' => 1, 'first_name' => 2, 'last_name' => 3, 'email' => 4, 'reset_key' => 5, 'new_email' => 6, 'new_email_request_time' => 7, 'home_address' => 8, 'city' => 9, 'state_prov' => 10, 'country' => 11, 'zip_postal' => 12, 'home_phone' => 13, 'cell_phone' => 14, 'business_phone' => 15, 'level' => 16, 'password' => 17, 'salt' => 18, 'created_at' => 19, 'updated_at' => 20, 'extra1' => 21, 'extra2' => 22, 'extra3' => 23, 'extra4' => 24, 'extra5' => 25, 'extra6' => 26, 'extra7' => 27, 'extra8' => 28, 'extra9' => 29, 'extra10' => 30, 'extra11' => 31, 'extra12' => 32, 'extra13' => 33, 'extra14' => 34, 'extra15' => 35, 'extra16' => 36, 'extra17' => 37, 'extra18' => 38, 'extra19' => 39, 'extra20' => 40, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new StudentMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. StudentPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(StudentPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(StudentPeer::ID);

		$criteria->addSelectColumn(StudentPeer::FMID);

		$criteria->addSelectColumn(StudentPeer::FIRST_NAME);

		$criteria->addSelectColumn(StudentPeer::LAST_NAME);

		$criteria->addSelectColumn(StudentPeer::EMAIL);

		$criteria->addSelectColumn(StudentPeer::RESET_KEY);

		$criteria->addSelectColumn(StudentPeer::NEW_EMAIL);

		$criteria->addSelectColumn(StudentPeer::NEW_EMAIL_REQUEST_TIME);

		$criteria->addSelectColumn(StudentPeer::HOME_ADDRESS);

		$criteria->addSelectColumn(StudentPeer::CITY);

		$criteria->addSelectColumn(StudentPeer::STATE_PROV);

		$criteria->addSelectColumn(StudentPeer::COUNTRY);

		$criteria->addSelectColumn(StudentPeer::ZIP_POSTAL);

		$criteria->addSelectColumn(StudentPeer::HOME_PHONE);

		$criteria->addSelectColumn(StudentPeer::CELL_PHONE);

		$criteria->addSelectColumn(StudentPeer::BUSINESS_PHONE);

		$criteria->addSelectColumn(StudentPeer::LEVEL);

		$criteria->addSelectColumn(StudentPeer::PASSWORD);

		$criteria->addSelectColumn(StudentPeer::SALT);

		$criteria->addSelectColumn(StudentPeer::CREATED_AT);

		$criteria->addSelectColumn(StudentPeer::UPDATED_AT);

		$criteria->addSelectColumn(StudentPeer::EXTRA1);

		$criteria->addSelectColumn(StudentPeer::EXTRA2);

		$criteria->addSelectColumn(StudentPeer::EXTRA3);

		$criteria->addSelectColumn(StudentPeer::EXTRA4);

		$criteria->addSelectColumn(StudentPeer::EXTRA5);

		$criteria->addSelectColumn(StudentPeer::EXTRA6);

		$criteria->addSelectColumn(StudentPeer::EXTRA7);

		$criteria->addSelectColumn(StudentPeer::EXTRA8);

		$criteria->addSelectColumn(StudentPeer::EXTRA9);

		$criteria->addSelectColumn(StudentPeer::EXTRA10);

		$criteria->addSelectColumn(StudentPeer::EXTRA11);

		$criteria->addSelectColumn(StudentPeer::EXTRA12);

		$criteria->addSelectColumn(StudentPeer::EXTRA13);

		$criteria->addSelectColumn(StudentPeer::EXTRA14);

		$criteria->addSelectColumn(StudentPeer::EXTRA15);

		$criteria->addSelectColumn(StudentPeer::EXTRA16);

		$criteria->addSelectColumn(StudentPeer::EXTRA17);

		$criteria->addSelectColumn(StudentPeer::EXTRA18);

		$criteria->addSelectColumn(StudentPeer::EXTRA19);

		$criteria->addSelectColumn(StudentPeer::EXTRA20);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(StudentPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			StudentPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseStudentPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseStudentPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Student
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = StudentPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return StudentPeer::populateObjects(StudentPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudentPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseStudentPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			StudentPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Student $value A Student object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Student $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Student object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Student) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Student object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Student Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = StudentPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = StudentPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = StudentPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				StudentPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return StudentPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Student or Criteria object.
	 *
	 * @param      mixed $values Criteria or Student object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudentPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseStudentPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Student object
		}

		if ($criteria->containsKey(StudentPeer::ID) && $criteria->keyContainsValue(StudentPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.StudentPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseStudentPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseStudentPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Student or Criteria object.
	 *
	 * @param      mixed $values Criteria or Student object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseStudentPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseStudentPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(StudentPeer::ID);
			$selectCriteria->add(StudentPeer::ID, $criteria->remove(StudentPeer::ID), $comparison);

		} else { // $values is Student object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseStudentPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseStudentPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the student table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += StudentPeer::doOnDeleteCascade(new Criteria(StudentPeer::DATABASE_NAME), $con);
			$affectedRows += BasePeer::doDeleteAll(StudentPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Student or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Student object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			StudentPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Student) {
			// invalidate the cache for this single object
			StudentPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(StudentPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				StudentPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += StudentPeer::doOnDeleteCascade($criteria, $con);
			
				// Because this db requires some delete cascade/set null emulation, we have to
				// clear the cached instance *after* the emulation has happened (since
				// instances get re-added by the select statement contained therein).
				if ($values instanceof Criteria) {
					StudentPeer::clearInstancePool();
				} else { // it's a PK or object
					StudentPeer::removeInstanceFromPool($values);
				}
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			// invalidate objects in EnrollmentPeer instance pool, since one or more of them may be deleted by ON DELETE CASCADE rule.
			EnrollmentPeer::clearInstancePool();

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * This is a method for emulating ON DELETE CASCADE for DBs that don't support this
	 * feature (like MySQL or SQLite).
	 *
	 * This method is not very speedy because it must perform a query first to get
	 * the implicated records and then perform the deletes by calling those Peer classes.
	 *
	 * This method should be used within a transaction if possible.
	 *
	 * @param      Criteria $criteria
	 * @param      PropelPDO $con
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	protected static function doOnDeleteCascade(Criteria $criteria, PropelPDO $con)
	{
		// initialize var to track total num of affected rows
		$affectedRows = 0;

		// first find the objects that are implicated by the $criteria
		$objects = StudentPeer::doSelect($criteria, $con);
		foreach ($objects as $obj) {


			// delete related Enrollment objects
			$c = new Criteria(EnrollmentPeer::DATABASE_NAME);
			
			$c->add(EnrollmentPeer::STUDENT_ID, $obj->getId());
			$affectedRows += EnrollmentPeer::doDelete($c, $con);
		}
		return $affectedRows;
	}

	/**
	 * Validates all modified columns of given Student object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Student $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Student $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(StudentPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(StudentPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(StudentPeer::DATABASE_NAME, StudentPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = StudentPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Student
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = StudentPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(StudentPeer::DATABASE_NAME);
		$criteria->add(StudentPeer::ID, $pk);

		$v = StudentPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(StudentPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(StudentPeer::DATABASE_NAME);
			$criteria->add(StudentPeer::ID, $pks, Criteria::IN);
			$objs = StudentPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseStudentPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the StudentPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the StudentPeer class:
//
// Propel::getDatabaseMap(StudentPeer::DATABASE_NAME)->addTableBuilder(StudentPeer::TABLE_NAME, StudentPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseStudentPeer::DATABASE_NAME)->addTableBuilder(BaseStudentPeer::TABLE_NAME, BaseStudentPeer::getMapBuilder());

