<?php

/**
 * Base static class for performing query and update operations on the 'event' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov 28 13:47:53 2011
 *
 * @package    lib.model.om
 */
abstract class BaseEventPeer {

	/** the default database name for this class */
	const DATABASE_NAME = 'propel';

	/** the table name for this class */
	const TABLE_NAME = 'event';

	/** A class that can be returned by this peer. */
	const CLASS_DEFAULT = 'lib.model.Event';

	/** The total number of columns. */
	const NUM_COLUMNS = 39;

	/** The number of lazy-loaded columns. */
	const NUM_LAZY_LOAD_COLUMNS = 0;

	/** the column name for the ID field */
	const ID = 'event.ID';

	/** the column name for the FMID field */
	const FMID = 'event.FMID';

	/** the column name for the NAME field */
	const NAME = 'event.NAME';

	/** the column name for the LOCATION field */
	const LOCATION = 'event.LOCATION';

	/** the column name for the COURSE_TYPE_ID field */
	const COURSE_TYPE_ID = 'event.COURSE_TYPE_ID';

	/** the column name for the START_DATE field */
	const START_DATE = 'event.START_DATE';

	/** the column name for the END_DATE field */
	const END_DATE = 'event.END_DATE';

	/** the column name for the MAX_ENROLLMENT field */
	const MAX_ENROLLMENT = 'event.MAX_ENROLLMENT';

	/** the column name for the CURRENT_ENROLLMENT field */
	const CURRENT_ENROLLMENT = 'event.CURRENT_ENROLLMENT';

	/** the column name for the MAX_WAITLIST field */
	const MAX_WAITLIST = 'event.MAX_WAITLIST';

	/** the column name for the CURRENT_WAITLIST field */
	const CURRENT_WAITLIST = 'event.CURRENT_WAITLIST';

	/** the column name for the MAX_ASSISTING_ENROLLMENT field */
	const MAX_ASSISTING_ENROLLMENT = 'event.MAX_ASSISTING_ENROLLMENT';

	/** the column name for the CURRENT_ASSISTING_ENROLLMENT field */
	const CURRENT_ASSISTING_ENROLLMENT = 'event.CURRENT_ASSISTING_ENROLLMENT';

	/** the column name for the MAX_ASSISTING_WAITLIST field */
	const MAX_ASSISTING_WAITLIST = 'event.MAX_ASSISTING_WAITLIST';

	/** the column name for the CURRENT_ASSISTING_WAITLIST field */
	const CURRENT_ASSISTING_WAITLIST = 'event.CURRENT_ASSISTING_WAITLIST';

	/** the column name for the BOOKING_LINK field */
	const BOOKING_LINK = 'event.BOOKING_LINK';

	/** the column name for the LEADER_NAME field */
	const LEADER_NAME = 'event.LEADER_NAME';

	/** the column name for the CREATED_AT field */
	const CREATED_AT = 'event.CREATED_AT';

	/** the column name for the UPDATED_AT field */
	const UPDATED_AT = 'event.UPDATED_AT';

	/** the column name for the EXTRA1 field */
	const EXTRA1 = 'event.EXTRA1';

	/** the column name for the EXTRA2 field */
	const EXTRA2 = 'event.EXTRA2';

	/** the column name for the EXTRA3 field */
	const EXTRA3 = 'event.EXTRA3';

	/** the column name for the EXTRA4 field */
	const EXTRA4 = 'event.EXTRA4';

	/** the column name for the EXTRA5 field */
	const EXTRA5 = 'event.EXTRA5';

	/** the column name for the EXTRA6 field */
	const EXTRA6 = 'event.EXTRA6';

	/** the column name for the EXTRA7 field */
	const EXTRA7 = 'event.EXTRA7';

	/** the column name for the EXTRA8 field */
	const EXTRA8 = 'event.EXTRA8';

	/** the column name for the EXTRA9 field */
	const EXTRA9 = 'event.EXTRA9';

	/** the column name for the EXTRA10 field */
	const EXTRA10 = 'event.EXTRA10';

	/** the column name for the EXTRA11 field */
	const EXTRA11 = 'event.EXTRA11';

	/** the column name for the EXTRA12 field */
	const EXTRA12 = 'event.EXTRA12';

	/** the column name for the EXTRA13 field */
	const EXTRA13 = 'event.EXTRA13';

	/** the column name for the EXTRA14 field */
	const EXTRA14 = 'event.EXTRA14';

	/** the column name for the EXTRA15 field */
	const EXTRA15 = 'event.EXTRA15';

	/** the column name for the EXTRA16 field */
	const EXTRA16 = 'event.EXTRA16';

	/** the column name for the EXTRA17 field */
	const EXTRA17 = 'event.EXTRA17';

	/** the column name for the EXTRA18 field */
	const EXTRA18 = 'event.EXTRA18';

	/** the column name for the EXTRA19 field */
	const EXTRA19 = 'event.EXTRA19';

	/** the column name for the EXTRA20 field */
	const EXTRA20 = 'event.EXTRA20';

	/**
	 * An identiy map to hold any loaded instances of Event objects.
	 * This must be public so that other peer classes can access this when hydrating from JOIN
	 * queries.
	 * @var        array Event[]
	 */
	public static $instances = array();

	/**
	 * The MapBuilder instance for this peer.
	 * @var        MapBuilder
	 */
	private static $mapBuilder = null;

	/**
	 * holds an array of fieldnames
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[self::TYPE_PHPNAME][0] = 'Id'
	 */
	private static $fieldNames = array (
		BasePeer::TYPE_PHPNAME => array ('Id', 'Fmid', 'Name', 'Location', 'CourseTypeId', 'StartDate', 'EndDate', 'MaxEnrollment', 'CurrentEnrollment', 'MaxWaitlist', 'CurrentWaitlist', 'MaxAssistingEnrollment', 'CurrentAssistingEnrollment', 'MaxAssistingWaitlist', 'CurrentAssistingWaitlist', 'BookingLink', 'LeaderName', 'CreatedAt', 'UpdatedAt', 'Extra1', 'Extra2', 'Extra3', 'Extra4', 'Extra5', 'Extra6', 'Extra7', 'Extra8', 'Extra9', 'Extra10', 'Extra11', 'Extra12', 'Extra13', 'Extra14', 'Extra15', 'Extra16', 'Extra17', 'Extra18', 'Extra19', 'Extra20', ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id', 'fmid', 'name', 'location', 'courseTypeId', 'startDate', 'endDate', 'maxEnrollment', 'currentEnrollment', 'maxWaitlist', 'currentWaitlist', 'maxAssistingEnrollment', 'currentAssistingEnrollment', 'maxAssistingWaitlist', 'currentAssistingWaitlist', 'bookingLink', 'leaderName', 'createdAt', 'updatedAt', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_COLNAME => array (self::ID, self::FMID, self::NAME, self::LOCATION, self::COURSE_TYPE_ID, self::START_DATE, self::END_DATE, self::MAX_ENROLLMENT, self::CURRENT_ENROLLMENT, self::MAX_WAITLIST, self::CURRENT_WAITLIST, self::MAX_ASSISTING_ENROLLMENT, self::CURRENT_ASSISTING_ENROLLMENT, self::MAX_ASSISTING_WAITLIST, self::CURRENT_ASSISTING_WAITLIST, self::BOOKING_LINK, self::LEADER_NAME, self::CREATED_AT, self::UPDATED_AT, self::EXTRA1, self::EXTRA2, self::EXTRA3, self::EXTRA4, self::EXTRA5, self::EXTRA6, self::EXTRA7, self::EXTRA8, self::EXTRA9, self::EXTRA10, self::EXTRA11, self::EXTRA12, self::EXTRA13, self::EXTRA14, self::EXTRA15, self::EXTRA16, self::EXTRA17, self::EXTRA18, self::EXTRA19, self::EXTRA20, ),
		BasePeer::TYPE_FIELDNAME => array ('id', 'fmid', 'name', 'location', 'course_type_id', 'start_date', 'end_date', 'max_enrollment', 'current_enrollment', 'max_waitlist', 'current_waitlist', 'max_assisting_enrollment', 'current_assisting_enrollment', 'max_assisting_waitlist', 'current_assisting_waitlist', 'booking_link', 'leader_name', 'created_at', 'updated_at', 'extra1', 'extra2', 'extra3', 'extra4', 'extra5', 'extra6', 'extra7', 'extra8', 'extra9', 'extra10', 'extra11', 'extra12', 'extra13', 'extra14', 'extra15', 'extra16', 'extra17', 'extra18', 'extra19', 'extra20', ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, )
	);

	/**
	 * holds an array of keys for quick access to the fieldnames array
	 *
	 * first dimension keys are the type constants
	 * e.g. self::$fieldNames[BasePeer::TYPE_PHPNAME]['Id'] = 0
	 */
	private static $fieldKeys = array (
		BasePeer::TYPE_PHPNAME => array ('Id' => 0, 'Fmid' => 1, 'Name' => 2, 'Location' => 3, 'CourseTypeId' => 4, 'StartDate' => 5, 'EndDate' => 6, 'MaxEnrollment' => 7, 'CurrentEnrollment' => 8, 'MaxWaitlist' => 9, 'CurrentWaitlist' => 10, 'MaxAssistingEnrollment' => 11, 'CurrentAssistingEnrollment' => 12, 'MaxAssistingWaitlist' => 13, 'CurrentAssistingWaitlist' => 14, 'BookingLink' => 15, 'LeaderName' => 16, 'CreatedAt' => 17, 'UpdatedAt' => 18, 'Extra1' => 19, 'Extra2' => 20, 'Extra3' => 21, 'Extra4' => 22, 'Extra5' => 23, 'Extra6' => 24, 'Extra7' => 25, 'Extra8' => 26, 'Extra9' => 27, 'Extra10' => 28, 'Extra11' => 29, 'Extra12' => 30, 'Extra13' => 31, 'Extra14' => 32, 'Extra15' => 33, 'Extra16' => 34, 'Extra17' => 35, 'Extra18' => 36, 'Extra19' => 37, 'Extra20' => 38, ),
		BasePeer::TYPE_STUDLYPHPNAME => array ('id' => 0, 'fmid' => 1, 'name' => 2, 'location' => 3, 'courseTypeId' => 4, 'startDate' => 5, 'endDate' => 6, 'maxEnrollment' => 7, 'currentEnrollment' => 8, 'maxWaitlist' => 9, 'currentWaitlist' => 10, 'maxAssistingEnrollment' => 11, 'currentAssistingEnrollment' => 12, 'maxAssistingWaitlist' => 13, 'currentAssistingWaitlist' => 14, 'bookingLink' => 15, 'leaderName' => 16, 'createdAt' => 17, 'updatedAt' => 18, 'extra1' => 19, 'extra2' => 20, 'extra3' => 21, 'extra4' => 22, 'extra5' => 23, 'extra6' => 24, 'extra7' => 25, 'extra8' => 26, 'extra9' => 27, 'extra10' => 28, 'extra11' => 29, 'extra12' => 30, 'extra13' => 31, 'extra14' => 32, 'extra15' => 33, 'extra16' => 34, 'extra17' => 35, 'extra18' => 36, 'extra19' => 37, 'extra20' => 38, ),
		BasePeer::TYPE_COLNAME => array (self::ID => 0, self::FMID => 1, self::NAME => 2, self::LOCATION => 3, self::COURSE_TYPE_ID => 4, self::START_DATE => 5, self::END_DATE => 6, self::MAX_ENROLLMENT => 7, self::CURRENT_ENROLLMENT => 8, self::MAX_WAITLIST => 9, self::CURRENT_WAITLIST => 10, self::MAX_ASSISTING_ENROLLMENT => 11, self::CURRENT_ASSISTING_ENROLLMENT => 12, self::MAX_ASSISTING_WAITLIST => 13, self::CURRENT_ASSISTING_WAITLIST => 14, self::BOOKING_LINK => 15, self::LEADER_NAME => 16, self::CREATED_AT => 17, self::UPDATED_AT => 18, self::EXTRA1 => 19, self::EXTRA2 => 20, self::EXTRA3 => 21, self::EXTRA4 => 22, self::EXTRA5 => 23, self::EXTRA6 => 24, self::EXTRA7 => 25, self::EXTRA8 => 26, self::EXTRA9 => 27, self::EXTRA10 => 28, self::EXTRA11 => 29, self::EXTRA12 => 30, self::EXTRA13 => 31, self::EXTRA14 => 32, self::EXTRA15 => 33, self::EXTRA16 => 34, self::EXTRA17 => 35, self::EXTRA18 => 36, self::EXTRA19 => 37, self::EXTRA20 => 38, ),
		BasePeer::TYPE_FIELDNAME => array ('id' => 0, 'fmid' => 1, 'name' => 2, 'location' => 3, 'course_type_id' => 4, 'start_date' => 5, 'end_date' => 6, 'max_enrollment' => 7, 'current_enrollment' => 8, 'max_waitlist' => 9, 'current_waitlist' => 10, 'max_assisting_enrollment' => 11, 'current_assisting_enrollment' => 12, 'max_assisting_waitlist' => 13, 'current_assisting_waitlist' => 14, 'booking_link' => 15, 'leader_name' => 16, 'created_at' => 17, 'updated_at' => 18, 'extra1' => 19, 'extra2' => 20, 'extra3' => 21, 'extra4' => 22, 'extra5' => 23, 'extra6' => 24, 'extra7' => 25, 'extra8' => 26, 'extra9' => 27, 'extra10' => 28, 'extra11' => 29, 'extra12' => 30, 'extra13' => 31, 'extra14' => 32, 'extra15' => 33, 'extra16' => 34, 'extra17' => 35, 'extra18' => 36, 'extra19' => 37, 'extra20' => 38, ),
		BasePeer::TYPE_NUM => array (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, )
	);

	/**
	 * Get a (singleton) instance of the MapBuilder for this peer class.
	 * @return     MapBuilder The map builder for this peer
	 */
	public static function getMapBuilder()
	{
		if (self::$mapBuilder === null) {
			self::$mapBuilder = new EventMapBuilder();
		}
		return self::$mapBuilder;
	}
	/**
	 * Translates a fieldname to another type
	 *
	 * @param      string $name field name
	 * @param      string $fromType One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                         BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @param      string $toType   One of the class type constants
	 * @return     string translated name of the field.
	 * @throws     PropelException - if the specified name could not be found in the fieldname mappings.
	 */
	static public function translateFieldName($name, $fromType, $toType)
	{
		$toNames = self::getFieldNames($toType);
		$key = isset(self::$fieldKeys[$fromType][$name]) ? self::$fieldKeys[$fromType][$name] : null;
		if ($key === null) {
			throw new PropelException("'$name' could not be found in the field names of type '$fromType'. These are: " . print_r(self::$fieldKeys[$fromType], true));
		}
		return $toNames[$key];
	}

	/**
	 * Returns an array of field names.
	 *
	 * @param      string $type The type of fieldnames to return:
	 *                      One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                      BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     array A list of field names
	 */

	static public function getFieldNames($type = BasePeer::TYPE_PHPNAME)
	{
		if (!array_key_exists($type, self::$fieldNames)) {
			throw new PropelException('Method getFieldNames() expects the parameter $type to be one of the class constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME, BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. ' . $type . ' was given.');
		}
		return self::$fieldNames[$type];
	}

	/**
	 * Convenience method which changes table.column to alias.column.
	 *
	 * Using this method you can maintain SQL abstraction while using column aliases.
	 * <code>
	 *		$c->addAlias("alias1", TablePeer::TABLE_NAME);
	 *		$c->addJoin(TablePeer::alias("alias1", TablePeer::PRIMARY_KEY_COLUMN), TablePeer::PRIMARY_KEY_COLUMN);
	 * </code>
	 * @param      string $alias The alias for the current table.
	 * @param      string $column The column name for current table. (i.e. EventPeer::COLUMN_NAME).
	 * @return     string
	 */
	public static function alias($alias, $column)
	{
		return str_replace(EventPeer::TABLE_NAME.'.', $alias.'.', $column);
	}

	/**
	 * Add all the columns needed to create a new object.
	 *
	 * Note: any columns that were marked with lazyLoad="true" in the
	 * XML schema will not be added to the select list and only loaded
	 * on demand.
	 *
	 * @param      criteria object containing the columns to add.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function addSelectColumns(Criteria $criteria)
	{

		$criteria->addSelectColumn(EventPeer::ID);

		$criteria->addSelectColumn(EventPeer::FMID);

		$criteria->addSelectColumn(EventPeer::NAME);

		$criteria->addSelectColumn(EventPeer::LOCATION);

		$criteria->addSelectColumn(EventPeer::COURSE_TYPE_ID);

		$criteria->addSelectColumn(EventPeer::START_DATE);

		$criteria->addSelectColumn(EventPeer::END_DATE);

		$criteria->addSelectColumn(EventPeer::MAX_ENROLLMENT);

		$criteria->addSelectColumn(EventPeer::CURRENT_ENROLLMENT);

		$criteria->addSelectColumn(EventPeer::MAX_WAITLIST);

		$criteria->addSelectColumn(EventPeer::CURRENT_WAITLIST);

		$criteria->addSelectColumn(EventPeer::MAX_ASSISTING_ENROLLMENT);

		$criteria->addSelectColumn(EventPeer::CURRENT_ASSISTING_ENROLLMENT);

		$criteria->addSelectColumn(EventPeer::MAX_ASSISTING_WAITLIST);

		$criteria->addSelectColumn(EventPeer::CURRENT_ASSISTING_WAITLIST);

		$criteria->addSelectColumn(EventPeer::BOOKING_LINK);

		$criteria->addSelectColumn(EventPeer::LEADER_NAME);

		$criteria->addSelectColumn(EventPeer::CREATED_AT);

		$criteria->addSelectColumn(EventPeer::UPDATED_AT);

		$criteria->addSelectColumn(EventPeer::EXTRA1);

		$criteria->addSelectColumn(EventPeer::EXTRA2);

		$criteria->addSelectColumn(EventPeer::EXTRA3);

		$criteria->addSelectColumn(EventPeer::EXTRA4);

		$criteria->addSelectColumn(EventPeer::EXTRA5);

		$criteria->addSelectColumn(EventPeer::EXTRA6);

		$criteria->addSelectColumn(EventPeer::EXTRA7);

		$criteria->addSelectColumn(EventPeer::EXTRA8);

		$criteria->addSelectColumn(EventPeer::EXTRA9);

		$criteria->addSelectColumn(EventPeer::EXTRA10);

		$criteria->addSelectColumn(EventPeer::EXTRA11);

		$criteria->addSelectColumn(EventPeer::EXTRA12);

		$criteria->addSelectColumn(EventPeer::EXTRA13);

		$criteria->addSelectColumn(EventPeer::EXTRA14);

		$criteria->addSelectColumn(EventPeer::EXTRA15);

		$criteria->addSelectColumn(EventPeer::EXTRA16);

		$criteria->addSelectColumn(EventPeer::EXTRA17);

		$criteria->addSelectColumn(EventPeer::EXTRA18);

		$criteria->addSelectColumn(EventPeer::EXTRA19);

		$criteria->addSelectColumn(EventPeer::EXTRA20);

	}

	/**
	 * Returns the number of rows matching criteria.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct Whether to select only distinct columns; deprecated: use Criteria->setDistinct() instead.
	 * @param      PropelPDO $con
	 * @return     int Number of matching rows.
	 */
	public static function doCount(Criteria $criteria, $distinct = false, PropelPDO $con = null)
	{
		// we may modify criteria, so copy it first
		$criteria = clone $criteria;

		// We need to set the primary table name, since in the case that there are no WHERE columns
		// it will be impossible for the BasePeer::createSelectSql() method to determine which
		// tables go into the FROM clause.
		$criteria->setPrimaryTableName(EventPeer::TABLE_NAME);

		if ($distinct && !in_array(Criteria::DISTINCT, $criteria->getSelectModifiers())) {
			$criteria->setDistinct();
		}

		if (!$criteria->hasSelectClause()) {
			EventPeer::addSelectColumns($criteria);
		}

		$criteria->clearOrderByColumns(); // ORDER BY won't ever affect the count
		$criteria->setDbName(self::DATABASE_NAME); // Set the correct dbName

		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}


    foreach (sfMixer::getCallables('BaseEventPeer:doCount:doCount') as $callable)
    {
      call_user_func($callable, 'BaseEventPeer', $criteria, $con);
    }


		// BasePeer returns a PDOStatement
		$stmt = BasePeer::doCount($criteria, $con);

		if ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$count = (int) $row[0];
		} else {
			$count = 0; // no rows returned; we infer that means 0 matches.
		}
		$stmt->closeCursor();
		return $count;
	}
	/**
	 * Method to select one object from the DB.
	 *
	 * @param      Criteria $criteria object used to create the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     Event
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelectOne(Criteria $criteria, PropelPDO $con = null)
	{
		$critcopy = clone $criteria;
		$critcopy->setLimit(1);
		$objects = EventPeer::doSelect($critcopy, $con);
		if ($objects) {
			return $objects[0];
		}
		return null;
	}
	/**
	 * Method to do selects.
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con
	 * @return     array Array of selected Objects
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doSelect(Criteria $criteria, PropelPDO $con = null)
	{
		return EventPeer::populateObjects(EventPeer::doSelectStmt($criteria, $con));
	}
	/**
	 * Prepares the Criteria object and uses the parent doSelect() method to execute a PDOStatement.
	 *
	 * Use this method directly if you want to work with an executed statement durirectly (for example
	 * to perform your own object hydration).
	 *
	 * @param      Criteria $criteria The Criteria object used to build the SELECT statement.
	 * @param      PropelPDO $con The connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 * @return     PDOStatement The executed PDOStatement object.
	 * @see        BasePeer::doSelect()
	 */
	public static function doSelectStmt(Criteria $criteria, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEventPeer:doSelectStmt:doSelectStmt') as $callable)
    {
      call_user_func($callable, 'BaseEventPeer', $criteria, $con);
    }


		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		if (!$criteria->hasSelectClause()) {
			$criteria = clone $criteria;
			EventPeer::addSelectColumns($criteria);
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		// BasePeer returns a PDOStatement
		return BasePeer::doSelect($criteria, $con);
	}
	/**
	 * Adds an object to the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doSelect*()
	 * methods in your stub classes -- you may need to explicitly add objects
	 * to the cache in order to ensure that the same objects are always returned by doSelect*()
	 * and retrieveByPK*() calls.
	 *
	 * @param      Event $value A Event object.
	 * @param      string $key (optional) key to use for instance map (for performance boost if key was already calculated externally).
	 */
	public static function addInstanceToPool(Event $obj, $key = null)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if ($key === null) {
				$key = (string) $obj->getId();
			} // if key === null
			self::$instances[$key] = $obj;
		}
	}

	/**
	 * Removes an object from the instance pool.
	 *
	 * Propel keeps cached copies of objects in an instance pool when they are retrieved
	 * from the database.  In some cases -- especially when you override doDelete
	 * methods in your stub classes -- you may need to explicitly remove objects
	 * from the cache in order to prevent returning objects that no longer exist.
	 *
	 * @param      mixed $value A Event object or a primary key value.
	 */
	public static function removeInstanceFromPool($value)
	{
		if (Propel::isInstancePoolingEnabled() && $value !== null) {
			if (is_object($value) && $value instanceof Event) {
				$key = (string) $value->getId();
			} elseif (is_scalar($value)) {
				// assume we've been passed a primary key
				$key = (string) $value;
			} else {
				$e = new PropelException("Invalid value passed to removeInstanceFromPool().  Expected primary key or Event object; got " . (is_object($value) ? get_class($value) . ' object.' : var_export($value,true)));
				throw $e;
			}

			unset(self::$instances[$key]);
		}
	} // removeInstanceFromPool()

	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      string $key The key (@see getPrimaryKeyHash()) for this instance.
	 * @return     Event Found object or NULL if 1) no instance exists for specified key or 2) instance pooling has been disabled.
	 * @see        getPrimaryKeyHash()
	 */
	public static function getInstanceFromPool($key)
	{
		if (Propel::isInstancePoolingEnabled()) {
			if (isset(self::$instances[$key])) {
				return self::$instances[$key];
			}
		}
		return null; // just to be explicit
	}
	
	/**
	 * Clear the instance pool.
	 *
	 * @return     void
	 */
	public static function clearInstancePool()
	{
		self::$instances = array();
	}
	
	/**
	 * Retrieves a string version of the primary key from the DB resultset row that can be used to uniquely identify a row in this table.
	 *
	 * For tables with a single-column primary key, that simple pkey value will be returned.  For tables with
	 * a multi-column primary key, a serialize()d version of the primary key will be returned.
	 *
	 * @param      array $row PropelPDO resultset row.
	 * @param      int $startcol The 0-based offset for reading from the resultset row.
	 * @return     string A string version of PK or NULL if the components of primary key in result array are all null.
	 */
	public static function getPrimaryKeyHashFromRow($row, $startcol = 0)
	{
		// If the PK cannot be derived from the row, return NULL.
		if ($row[$startcol + 0] === null) {
			return null;
		}
		return (string) $row[$startcol + 0];
	}

	/**
	 * The returned array will contain objects of the default type or
	 * objects that inherit from the default.
	 *
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function populateObjects(PDOStatement $stmt)
	{
		$results = array();
	
		// set the class once to avoid overhead in the loop
		$cls = EventPeer::getOMClass();
		$cls = substr('.'.$cls, strrpos('.'.$cls, '.') + 1);
		// populate the object(s)
		while ($row = $stmt->fetch(PDO::FETCH_NUM)) {
			$key = EventPeer::getPrimaryKeyHashFromRow($row, 0);
			if (null !== ($obj = EventPeer::getInstanceFromPool($key))) {
				// We no longer rehydrate the object, since this can cause data loss.
				// See http://propel.phpdb.org/trac/ticket/509
				// $obj->hydrate($row, 0, true); // rehydrate
				$results[] = $obj;
			} else {
		
				$obj = new $cls();
				$obj->hydrate($row);
				$results[] = $obj;
				EventPeer::addInstanceToPool($obj, $key);
			} // if key exists
		}
		$stmt->closeCursor();
		return $results;
	}

  static public function getUniqueColumnNames()
  {
    return array();
  }
	/**
	 * Returns the TableMap related to this peer.
	 * This method is not needed for general use but a specific application could have a need.
	 * @return     TableMap
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function getTableMap()
	{
		return Propel::getDatabaseMap(self::DATABASE_NAME)->getTable(self::TABLE_NAME);
	}

	/**
	 * The class that the Peer will make instances of.
	 *
	 * This uses a dot-path notation which is tranalted into a path
	 * relative to a location on the PHP include_path.
	 * (e.g. path.to.MyClass -> 'path/to/MyClass.php')
	 *
	 * @return     string path.to.ClassName
	 */
	public static function getOMClass()
	{
		return EventPeer::CLASS_DEFAULT;
	}

	/**
	 * Method perform an INSERT on the database, given a Event or Criteria object.
	 *
	 * @param      mixed $values Criteria or Event object containing data that is used to create the INSERT statement.
	 * @param      PropelPDO $con the PropelPDO connection to use
	 * @return     mixed The new primary key.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doInsert($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEventPeer:doInsert:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseEventPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity
		} else {
			$criteria = $values->buildCriteria(); // build Criteria from Event object
		}

		if ($criteria->containsKey(EventPeer::ID) && $criteria->keyContainsValue(EventPeer::ID) ) {
			throw new PropelException('Cannot insert a value for auto-increment primary key ('.EventPeer::ID.')');
		}


		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		try {
			// use transaction because $criteria could contain info
			// for more than one table (I guess, conceivably)
			$con->beginTransaction();
			$pk = BasePeer::doInsert($criteria, $con);
			$con->commit();
		} catch(PropelException $e) {
			$con->rollBack();
			throw $e;
		}

		
    foreach (sfMixer::getCallables('BaseEventPeer:doInsert:post') as $callable)
    {
      call_user_func($callable, 'BaseEventPeer', $values, $con, $pk);
    }

    return $pk;
	}

	/**
	 * Method perform an UPDATE on the database, given a Event or Criteria object.
	 *
	 * @param      mixed $values Criteria or Event object containing data that is used to create the UPDATE statement.
	 * @param      PropelPDO $con The connection to use (specify PropelPDO connection object to exert more control over transactions).
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function doUpdate($values, PropelPDO $con = null)
	{

    foreach (sfMixer::getCallables('BaseEventPeer:doUpdate:pre') as $callable)
    {
      $ret = call_user_func($callable, 'BaseEventPeer', $values, $con);
      if (false !== $ret)
      {
        return $ret;
      }
    }


		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		$selectCriteria = new Criteria(self::DATABASE_NAME);

		if ($values instanceof Criteria) {
			$criteria = clone $values; // rename for clarity

			$comparison = $criteria->getComparison(EventPeer::ID);
			$selectCriteria->add(EventPeer::ID, $criteria->remove(EventPeer::ID), $comparison);

		} else { // $values is Event object
			$criteria = $values->buildCriteria(); // gets full criteria
			$selectCriteria = $values->buildPkeyCriteria(); // gets criteria w/ primary key(s)
		}

		// set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$ret = BasePeer::doUpdate($selectCriteria, $criteria, $con);
	

    foreach (sfMixer::getCallables('BaseEventPeer:doUpdate:post') as $callable)
    {
      call_user_func($callable, 'BaseEventPeer', $values, $con, $ret);
    }

    return $ret;
  }

	/**
	 * Method to DELETE all rows from the event table.
	 *
	 * @return     int The number of affected rows (if supported by underlying database driver).
	 */
	public static function doDeleteAll($con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		$affectedRows = 0; // initialize var to track total num of affected rows
		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			$affectedRows += BasePeer::doDeleteAll(EventPeer::TABLE_NAME, $con);
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Method perform a DELETE on the database, given a Event or Criteria object OR a primary key value.
	 *
	 * @param      mixed $values Criteria or Event object or primary key or array of primary keys
	 *              which is used to create the DELETE statement
	 * @param      PropelPDO $con the connection to use
	 * @return     int 	The number of affected rows (if supported by underlying database driver).  This includes CASCADE-related rows
	 *				if supported by native driver or if emulated using Propel.
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	 public static function doDelete($values, PropelPDO $con = null)
	 {
		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}

		if ($values instanceof Criteria) {
			// invalidate the cache for all objects of this type, since we have no
			// way of knowing (without running a query) what objects should be invalidated
			// from the cache based on this Criteria.
			EventPeer::clearInstancePool();

			// rename for clarity
			$criteria = clone $values;
		} elseif ($values instanceof Event) {
			// invalidate the cache for this single object
			EventPeer::removeInstanceFromPool($values);
			// create criteria based on pk values
			$criteria = $values->buildPkeyCriteria();
		} else {
			// it must be the primary key



			$criteria = new Criteria(self::DATABASE_NAME);
			$criteria->add(EventPeer::ID, (array) $values, Criteria::IN);

			foreach ((array) $values as $singleval) {
				// we can invalidate the cache for this single object
				EventPeer::removeInstanceFromPool($singleval);
			}
		}

		// Set the correct dbName
		$criteria->setDbName(self::DATABASE_NAME);

		$affectedRows = 0; // initialize var to track total num of affected rows

		try {
			// use transaction because $criteria could contain info
			// for more than one table or we could emulating ON DELETE CASCADE, etc.
			$con->beginTransaction();
			
			$affectedRows += BasePeer::doDelete($criteria, $con);

			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Validates all modified columns of given Event object.
	 * If parameter $columns is either a single column name or an array of column names
	 * than only those columns are validated.
	 *
	 * NOTICE: This does not apply to primary or foreign keys for now.
	 *
	 * @param      Event $obj The object to validate.
	 * @param      mixed $cols Column name or array of column names.
	 *
	 * @return     mixed TRUE if all columns are valid or the error message of the first invalid column.
	 */
	public static function doValidate(Event $obj, $cols = null)
	{
		$columns = array();

		if ($cols) {
			$dbMap = Propel::getDatabaseMap(EventPeer::DATABASE_NAME);
			$tableMap = $dbMap->getTable(EventPeer::TABLE_NAME);

			if (! is_array($cols)) {
				$cols = array($cols);
			}

			foreach ($cols as $colName) {
				if ($tableMap->containsColumn($colName)) {
					$get = 'get' . $tableMap->getColumn($colName)->getPhpName();
					$columns[$colName] = $obj->$get();
				}
			}
		} else {

		}

		$res =  BasePeer::doValidate(EventPeer::DATABASE_NAME, EventPeer::TABLE_NAME, $columns);
    if ($res !== true) {
        $request = sfContext::getInstance()->getRequest();
        foreach ($res as $failed) {
            $col = EventPeer::translateFieldname($failed->getColumn(), BasePeer::TYPE_COLNAME, BasePeer::TYPE_PHPNAME);
        }
    }

    return $res;
	}

	/**
	 * Retrieve a single object by pkey.
	 *
	 * @param      int $pk the primary key.
	 * @param      PropelPDO $con the connection to use
	 * @return     Event
	 */
	public static function retrieveByPK($pk, PropelPDO $con = null)
	{

		if (null !== ($obj = EventPeer::getInstanceFromPool((string) $pk))) {
			return $obj;
		}

		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$criteria = new Criteria(EventPeer::DATABASE_NAME);
		$criteria->add(EventPeer::ID, $pk);

		$v = EventPeer::doSelect($criteria, $con);

		return !empty($v) > 0 ? $v[0] : null;
	}

	/**
	 * Retrieve multiple objects by pkey.
	 *
	 * @param      array $pks List of primary keys
	 * @param      PropelPDO $con the connection to use
	 * @throws     PropelException Any exceptions caught during processing will be
	 *		 rethrown wrapped into a PropelException.
	 */
	public static function retrieveByPKs($pks, PropelPDO $con = null)
	{
		if ($con === null) {
			$con = Propel::getConnection(EventPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		$objs = null;
		if (empty($pks)) {
			$objs = array();
		} else {
			$criteria = new Criteria(EventPeer::DATABASE_NAME);
			$criteria->add(EventPeer::ID, $pks, Criteria::IN);
			$objs = EventPeer::doSelect($criteria, $con);
		}
		return $objs;
	}

} // BaseEventPeer

// This is the static code needed to register the MapBuilder for this table with the main Propel class.
//
// NOTE: This static code cannot call methods on the EventPeer class, because it is not defined yet.
// If you need to use overridden methods, you can add this code to the bottom of the EventPeer class:
//
// Propel::getDatabaseMap(EventPeer::DATABASE_NAME)->addTableBuilder(EventPeer::TABLE_NAME, EventPeer::getMapBuilder());
//
// Doing so will effectively overwrite the registration below.

Propel::getDatabaseMap(BaseEventPeer::DATABASE_NAME)->addTableBuilder(BaseEventPeer::TABLE_NAME, BaseEventPeer::getMapBuilder());

