
;; menu.el - quick access menus for emacs editor
;; *** auto generated by bin/symenu ***
;; To use this menu, load into buffer and then ESC-X eval-buffer
;; T. Beutel

(defvar my-menu nil "my menu")

 (easy-menu-define my-menu global-map "My own menu"
 '("Modules"
))

 (easy-menu-define my-menu global-map "My own menu"
 '("Forms"
))

 (easy-menu-define my-menu global-map "My own menu"
 '("Models"
))

 (easy-menu-define my-menu global-map "My own menu"
 '("Layout"
))
