<?php


/**
 * This class adds structure of 'student' table to 'propel' DatabaseMap object.
 *
 *
 * This class was autogenerated by Propel 1.3.0-dev on:
 *
 * Mon Nov 28 13:47:54 2011
 *
 *
 * These statically-built map classes are used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class StudentMapBuilder implements MapBuilder {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.StudentMapBuilder';

	/**
	 * The database map.
	 */
	private $dbMap;

	/**
	 * Tells us if this DatabaseMapBuilder is built so that we
	 * don't have to re-build it every time.
	 *
	 * @return     boolean true if this DatabaseMapBuilder is built, false otherwise.
	 */
	public function isBuilt()
	{
		return ($this->dbMap !== null);
	}

	/**
	 * Gets the databasemap this map builder built.
	 *
	 * @return     the databasemap
	 */
	public function getDatabaseMap()
	{
		return $this->dbMap;
	}

	/**
	 * The doBuild() method builds the DatabaseMap
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function doBuild()
	{
		$this->dbMap = Propel::getDatabaseMap(StudentPeer::DATABASE_NAME);

		$tMap = $this->dbMap->addTable(StudentPeer::TABLE_NAME);
		$tMap->setPhpName('Student');
		$tMap->setClassname('Student');

		$tMap->setUseIdGenerator(true);

		$tMap->addPrimaryKey('ID', 'Id', 'INTEGER', true, null);

		$tMap->addColumn('FMID', 'Fmid', 'INTEGER', false, null);

		$tMap->addColumn('FIRST_NAME', 'FirstName', 'VARCHAR', false, 100);

		$tMap->addColumn('LAST_NAME', 'LastName', 'VARCHAR', false, 100);

		$tMap->addColumn('EMAIL', 'Email', 'VARCHAR', false, 100);

		$tMap->addColumn('RESET_KEY', 'ResetKey', 'VARCHAR', false, 100);

		$tMap->addColumn('NEW_EMAIL', 'NewEmail', 'VARCHAR', false, 100);

		$tMap->addColumn('NEW_EMAIL_REQUEST_TIME', 'NewEmailRequestTime', 'TIMESTAMP', false, null);

		$tMap->addColumn('HOME_ADDRESS', 'HomeAddress', 'LONGVARCHAR', false, null);

		$tMap->addColumn('CITY', 'City', 'LONGVARCHAR', false, null);

		$tMap->addColumn('STATE_PROV', 'StateProv', 'LONGVARCHAR', false, null);

		$tMap->addColumn('COUNTRY', 'Country', 'LONGVARCHAR', false, null);

		$tMap->addColumn('ZIP_POSTAL', 'ZipPostal', 'LONGVARCHAR', false, null);

		$tMap->addColumn('HOME_PHONE', 'HomePhone', 'VARCHAR', false, 100);

		$tMap->addColumn('CELL_PHONE', 'CellPhone', 'VARCHAR', false, 100);

		$tMap->addColumn('BUSINESS_PHONE', 'BusinessPhone', 'VARCHAR', false, 100);

		$tMap->addColumn('LEVEL', 'Level', 'INTEGER', false, null);

		$tMap->addColumn('PASSWORD', 'Password', 'VARCHAR', false, 100);

		$tMap->addColumn('SALT', 'Salt', 'VARCHAR', false, 100);

		$tMap->addColumn('CREATED_AT', 'CreatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('UPDATED_AT', 'UpdatedAt', 'TIMESTAMP', false, null);

		$tMap->addColumn('EXTRA1', 'Extra1', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA2', 'Extra2', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA3', 'Extra3', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA4', 'Extra4', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA5', 'Extra5', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA6', 'Extra6', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA7', 'Extra7', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA8', 'Extra8', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA9', 'Extra9', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA10', 'Extra10', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA11', 'Extra11', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA12', 'Extra12', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA13', 'Extra13', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA14', 'Extra14', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA15', 'Extra15', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA16', 'Extra16', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA17', 'Extra17', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA18', 'Extra18', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA19', 'Extra19', 'LONGVARCHAR', false, null);

		$tMap->addColumn('EXTRA20', 'Extra20', 'LONGVARCHAR', false, null);

	} // doBuild()

} // StudentMapBuilder
