<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2013/10/22 13:13:03
sfConfig::add(array(
  'app_ctidatabase_server' => '127.0.0.1',
  'app_ctidatabase_port' => 3306,
  'app_ctidatabase_user' => 'cticoaches',
  'app_ctidatabase_password' => NULL,
  'app_webcomp_postkey' => 'fjgh15t',
  'app_webcomp_postkey2' => 'fjgh12fgt',
  'app_webcomp_baseurl' => 'http://crm.thecoaches.com/fmi-test/webcomp2_newFM',
  'app_webcomp_authen' => 'authenticate.php',
  'app_webcomp_recordexists' => 'portal_record_exists.php',
  'app_webcomp_newpw' => 'set_pw.php',
  'app_webcomp_commlog' => 'new_commlog.php',
  'app_webcomp_account' => 'portal_account.php',
  'app_webcomp_account_update' => 'portal_account_update.php',
  'app_webcomp_account_email' => 'portal_account_email.php',
  'app_webcomp_register' => 'portal_course_register.php',
  'app_webcomp_cancel' => 'portal_course_cancel.php',
  'app_webcomp_waitlist' => 'portal_course_waitlist.php',
  'app_webcomp_unenroll' => 'portal_unenroll.php',
  'app_webcomp_unwaitlist' => 'portal_unwaitlist.php',
  'app_webcomp_enrollletter' => 'portal_enroll_letter.php',
  'app_webcomp_waitlistletter' => 'portal_waitlist_letter.php',
  'app_webcomp_events' => 'portal_events.php',
  'app_webcomp_courses' => 'portal_courses.php',
));
