<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2013/10/22 13:13:03

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=portaldb',
  'username' => 'portaluser',
  'password' => '2wSDe3',
  'encoding' => 'utf8',
  'port' => 3306,
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
