<?php
// auto-generated by sfSecurityConfigHandler
// date: 2013/10/22 13:13:04
$this->security = array (
  'all' => 
  array (
    'is_secure' => true,
  ),
  'index' => 
  array (
    'is_secure' => false,
  ),
  'error404' => 
  array (
    'is_secure' => false,
  ),
  'basictemplate' => 
  array (
    'is_secure' => false,
  ),
  'problem' => 
  array (
    'is_secure' => false,
  ),
  'login' => 
  array (
    'is_secure' => false,
  ),
  'maintenance' => 
  array (
    'is_secure' => false,
  ),
  'logout' => 
  array (
    'is_secure' => false,
  ),
  'loginprocess' => 
  array (
    'is_secure' => false,
  ),
  'requestnewpassword' => 
  array (
    'is_secure' => false,
  ),
  'requestnewpasswordprocess' => 
  array (
    'is_secure' => false,
  ),
  'newemail' => 
  array (
    'is_secure' => false,
  ),
  'newpassword' => 
  array (
    'is_secure' => false,
  ),
  'newpasswordprocess' => 
  array (
    'is_secure' => false,
  ),
  'updateeventsfromfm' => 
  array (
    'is_secure' => false,
  ),
  'checkassistingwaitlists' => 
  array (
    'is_secure' => false,
  ),
);
