
;; menu.el - quick access menus for emacs editor
;; *** auto generated by bin/symenu ***
;; To use this menu, load into buffer and then ESC-X eval-buffer
;; T. Beutel

(defvar my-menu nil "my menu")
                                                                                     
(defun TODO-file ()                                                                           
 (interactive)                                                                                
  (let (mybuffer)                                                                             
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/TODO"))                                                   
 )                                                                                            
)                                                                                             

(defun account-actions ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/account/actions/actions.class.php"))
 )
)

(defun account-edit ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/account/templates/editSuccess.php"))
 )
)

(defun account-index ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/account/templates/indexSuccess.php"))
 )
)

(defun admin-actions ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/admin/actions/actions.class.php"))
 )
)

(defun admin-index ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/admin/templates/indexSuccess.php"))
 )
)

(defun assisting-actions ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/actions/actions.class.php"))
 )
)

(defun assisting-index ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/indexSuccess.php"))
 )
)

(defun assisting-regAssist ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/regAssistSuccess.php"))
 )
)

(defun assisting-registerInfo ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/registerInfoSuccess.php"))
 )
)

(defun assisting-registerStep1 ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/registerStep1Success.php"))
 )
)

(defun assisting-registerStep2 ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/registerStep2Success.php"))
 )
)

(defun assisting-registerThankYou ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/registerThankYouSuccess.php"))
 )
)

(defun assisting-registerTryAgainLater ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/registerTryAgainLaterSuccess.php"))
 )
)

(defun assisting-registration ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/registrationSuccess.php"))
 )
)

(defun assisting-waitlistInfo ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/assisting/templates/waitlistInfoSuccess.php"))
 )
)

(defun event-actions ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/actions/actions.class.php"))
 )
)

(defun event-eventInfo ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/eventInfoSuccess.php"))
 )
)

(defun event-index ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/indexSuccess.php"))
 )
)

(defun event-registerInfo ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/registerInfoSuccess.php"))
 )
)

(defun event-registerNotEligible ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/registerNotEligibleSuccess.php"))
 )
)

(defun event-register ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/registerSuccess.php"))
 )
)

(defun event-registerThankYou ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/registerThankYouSuccess.php"))
 )
)

(defun event-registration ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/registrationSuccess.php"))
 )
)

(defun event-waitlistInfo ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/waitlistInfoSuccess.php"))
 )
)

(defun event-waitlistThankYou ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/event/templates/waitlistThankYouSuccess.php"))
 )
)

(defun main-actions ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/actions/actions.class.php"))
 )
)

(defun main-basicTemplate ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/basicTemplateSuccess.php"))
 )
)

(defun main-cancelConfirmation ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/cancelConfirmationSuccess.php"))
 )
)

(defun main-cancel ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/cancelSuccess.php"))
 )
)

(defun main-help ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/helpSuccess.php"))
 )
)

(defun main-index ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/indexSuccess.php"))
 )
)

(defun main-login ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/loginSuccess.php"))
 )
)

(defun main-logout ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/logoutSuccess.php"))
 )
)

(defun main-maintenance ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/maintenanceSuccess.php"))
 )
)

(defun main-mySchedule2 ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/mySchedule2Success.php"))
 )
)

(defun main-mySchedule3 ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/mySchedule3Success.php"))
 )
)

(defun main-mySchedule ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/myScheduleSuccess.php"))
 )
)

(defun main-newEmail ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/newEmailSuccess.php"))
 )
)

(defun main-newPassword ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/newPasswordSuccess.php"))
 )
)

(defun main-problem ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/problemSuccess.php"))
 )
)

(defun main-requestNewPasswordProcess ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/requestNewPasswordProcessSuccess.php"))
 )
)

(defun main-requestNewPassword ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/requestNewPasswordSuccess.php"))
 )
)

(defun main-updateEventsFromFM ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/modules/main/templates/updateEventsFromFMSuccess.php"))
 )
)

 (easy-menu-define my-menu global-map "My own menu"
 '("Modules"
                                                                                 
 ("TODO"                                                                                      
 ["TODO" TODO-file t]                                                                         
)                                                                                             

 ("account"
 ["actions" account-actions t]

 ["edit" account-edit t]

 ["index" account-index t]
)

 ("admin"
 ["actions" admin-actions t]

 ["index" admin-index t]
)

 ("assisting"
 ["actions" assisting-actions t]

 ["index" assisting-index t]

 ["regAssist" assisting-regAssist t]

 ["registerInfo" assisting-registerInfo t]

 ["registerStep1" assisting-registerStep1 t]

 ["registerStep2" assisting-registerStep2 t]

 ["registerThankYou" assisting-registerThankYou t]

 ["registerTryAgainLater" assisting-registerTryAgainLater t]

 ["registration" assisting-registration t]

 ["waitlistInfo" assisting-waitlistInfo t]
)

 ("event"
 ["actions" event-actions t]

 ["eventInfo" event-eventInfo t]

 ["index" event-index t]

 ["registerInfo" event-registerInfo t]

 ["registerNotEligible" event-registerNotEligible t]

 ["register" event-register t]

 ["registerThankYou" event-registerThankYou t]

 ["registration" event-registration t]

 ["waitlistInfo" event-waitlistInfo t]

 ["waitlistThankYou" event-waitlistThankYou t]
)

 ("main"
 ["actions" main-actions t]

 ["basicTemplate" main-basicTemplate t]

 ["cancelConfirmation" main-cancelConfirmation t]

 ["cancel" main-cancel t]

 ["help" main-help t]

 ["index" main-index t]

 ["login" main-login t]

 ["logout" main-logout t]

 ["maintenance" main-maintenance t]

 ["mySchedule2" main-mySchedule2 t]

 ["mySchedule3" main-mySchedule3 t]

 ["mySchedule" main-mySchedule t]

 ["newEmail" main-newEmail t]

 ["newPassword" main-newPassword t]

 ["problem" main-problem t]

 ["requestNewPasswordProcess" main-requestNewPasswordProcess t]

 ["requestNewPassword" main-requestNewPassword t]

 ["updateEventsFromFM" main-updateEventsFromFM t]
)
))

(defun form-Enrollment ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/form/EnrollmentForm.class.php"))
 )
)

(defun form-Event ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/form/EventForm.class.php"))
 )
)

(defun form-Student ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/form/StudentForm.class.php"))
 )
)

(defun form-Waitlist ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/form/WaitlistForm.class.php"))
 )
)

 (easy-menu-define my-menu global-map "My own menu"
 '("Forms"

 ["Enrollment" form-Enrollment t]

 ["Event" form-Event t]

 ["Student" form-Student t]

 ["Waitlist" form-Waitlist t]
))

(defun model-Enrollment ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/Enrollment.php"))
 )
)

(defun model-EnrollmentPeer ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/EnrollmentPeer.php"))
 )
)

(defun model-Event ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/Event.php"))
 )
)

(defun model-EventPeer ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/EventPeer.php"))
 )
)

(defun model-Student ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/Student.php"))
 )
)

(defun model-StudentPeer ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/StudentPeer.php"))
 )
)

(defun model-Waitlist ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/Waitlist.php"))
 )
)

(defun model-WaitlistPeer ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/model/WaitlistPeer.php"))
 )
)

(defun model-myUser.class ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/lib/myUser.class.php"))
 )
)

(defun model-commonTools.class ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/lib/commonTools.class.php"))
 )
)

 (easy-menu-define my-menu global-map "My own menu"
 '("Models"

 ["Enrollment" model-Enrollment t]

 ["EnrollmentPeer" model-EnrollmentPeer t]

 ["Event" model-Event t]

 ["EventPeer" model-EventPeer t]

 ["Student" model-Student t]

 ["StudentPeer" model-StudentPeer t]

 ["Waitlist" model-Waitlist t]

 ["WaitlistPeer" model-WaitlistPeer t]

 ["myUser.class" model-myUser.class t]

 ["commonTools.class" model-commonTools.class t]
))

(defun layout-bare ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/templates/bare.php"))
 )
)

(defun layout-layout-assisting ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/templates/layout-assisting.php"))
 )
)

(defun layout-layout-generic ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/templates/layout-generic.php"))
 )
)

(defun layout-layout-login ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/templates/layout-login.php"))
 )
)

(defun layout-layout-simple ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/templates/layout-simple.php"))
 )
)

(defun layout-layout ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/apps/frontend/templates/layout.php"))
 )
)

(defun layout-colorbox ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/web/css/colorbox.css"))
 )
)

(defun layout-main ()
 (interactive)
  (let (mybuffer)
    (setq mybuffer (find-file "/thomas@corp9.modelsmith.com:/www/www.thecoaches.com/portal/web/css/main.css"))
 )
)

 (easy-menu-define my-menu global-map "My own menu"
 '("Layout"

 ["bare.php" layout-bare t]

 ["layout-assisting.php" layout-layout-assisting t]

 ["layout-generic.php" layout-layout-generic t]

 ["layout-login.php" layout-layout-login t]

 ["layout-simple.php" layout-layout-simple t]

 ["layout.php" layout-layout t]

 ["colorbox.css" layout-colorbox t]

 ["main.css" layout-main t]
))
